### ISSUE TITLE
zoom doesn't work with forceNetwork

### ISSUE THREAD

**Issue by christophergandrud** [christophergandrud/networkD3#1]

**Comment by happyshows** [comment]
Hi Chris,

I'm wondering if there's any progress on zoom function inside shiny? Like the one implemented by timelyportfolio/svgPanZoom
http://www.buildingwidgets.com/blog

Thanks.

**Comment by christophergandrud** [comment]
Hi @happyshows 

Sorry I've been really busy with work/pushing out some changes to other packages, so personally haven't made progress on this. Any pull requests would be much appreciated.

**Comment by timelyportfolio** [comment]
I could possibly get to it.  I like this http://plnkr.co/edit/cxLlvIlmo1Y6vJyPs6N9?p=preview as a model implementation.  @happyshows is that what you would like to see?

**Comment by timelyportfolio** [comment]
Wait, I think it is already in [here](https://github.com/christophergandrud/networkD3/blob/master/inst/htmlwidgets/forceNetwork.js#L55-L76)  and just needs the R options available.  I'll submit a pull.

**Comment by christophergandrud** [comment]
I have to remember why it wasn't working exactly (it got pushed to the back of my queue). It worked in the old d3Network, but never for Shiny.

**Comment by timelyportfolio** [comment]
Ok, I see why it is there but not working.  I'll try to work on for the next couple minutes to scope the difficulty.

**Comment by happyshows** [comment]
@timelyportfolio thanks. I'm currently working on a customized version of Chris' d3network. I need to fix the coordinates of nodes. I think I can create a minimal example and share with you later on.

**Comment by timelyportfolio** [comment]
so turn force off also?

**Comment by timelyportfolio** [comment]
@christophergandrud here is working code on my machine https://github.com/timelyportfolio/networkD3/tree/feature/zoom-force .  I'll wait to submit pull until I hear from you that it works for you and that you like the change.

@happyshows, since you have a custom implementation, you can inspect the R and JS to see one way  we can add zoom.  Let me know if it makes sense.

**Comment by happyshows** [comment]
@timelyportfolio I tried your branch of networkD3, it doesn't seem to work in Shiny on my machine. (I simply copied pasted the code under inst folder) Thanks for the prompt reply.

**Comment by timelyportfolio** [comment]
Darn, probably something to do with Shiny exerting control over some events.  Did it work for you in a non-shiny example?

**Comment by happyshows** [comment]
I just tried the following code (in Rstudio viewer or chrome)

src <- c("A", "A", "A", "A", "B", "B", "C", "C", "D")
target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
networkData <- data.frame(src, target)
simpleNetwork(networkData)

wasn't able to zoom in or out....

The reason I wanted this zoom feature on shiny is I am plotting multiple diagrams / tab on a multi tab menu.
The forcenetwork diagrams are crowded with nodes, most of the time it's hard for user to see the details. It would be very neat if zoom is possible.

**Comment by timelyportfolio** [comment]
Oh, I only changed `forceNetwork`.  I'll add to `simpleNetwork` also.

**Comment by timelyportfolio** [comment]
see if `simpleNetwork` works now based on https://github.com/timelyportfolio/networkD3/commit/3f4eddc9a105e5a080de48e0cfa9b1cbf10bdd46

**Comment by happyshows** [comment]
@timelyportfolio Still not working.
Just double check on the step to install packages (I'm new to github)
 I downloaded from here: https://github.com/timelyportfolio/networkD3/tree/feature/zoom-force
renamed the zip to networkD3
unzipped and install('networkD3'), library('networkD3') and ran the code.

Neither simpleNetwork nor forceNetwork seem to work.

**Comment by timelyportfolio** [comment]
Forgot to make the change to add `zoom` parameter on the R side.  Sorry, please try it now. Best way would be to do

```
devtools::install_github("timelyportfolio/networkD3@feature/zoom-force")
library(networkD3)

# Fake data
Source <- c("A", "A", "A", "A", "B", "B", "C", "C", "D")
Target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
NetworkData <- data.frame(Source, Target)

# Create graph
simpleNetwork(NetworkData, zoom = T)
```

**Comment by happyshows** [comment]
@timelyportfolio Confirmed, it's working in standalone mode. Shiny still not working.

Thanks.

**Comment by timelyportfolio** [comment]
What happens if you try this Shiny example from the `networkD3` docs with just `zoom = T` added?

```
library(shiny)
library(networkD3)

data(MisLinks)
data(MisNodes)

#### Server ####
server <- function(input, output) {
  
  output$simple <- renderSimpleNetwork({
    src <- c("A", "A", "A", "A", "B", "B", "C", "C", "D")
    target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
    networkData <- data.frame(src, target)
    simpleNetwork(networkData, opacity = input$opacity, zoom = T)
  })
  
  output$force <- renderForceNetwork({
    forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
                 Target = "target", Value = "value", NodeID = "name",
                 Group = "group", opacity = input$opacity, zoom = T)
  })
  
}

#### UI ####

ui <- shinyUI(fluidPage(
  
  titlePanel("Shiny networkD3 "),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("opacity", "Opacity (not for Sankey)", 0.6, min = 0.1,
                  max = 1, step = .1)
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Simple Network", simpleNetworkOutput("simple")),
        tabPanel("Force Network", forceNetworkOutput("force"))
      )
    )
  )
))

#### Run ####
shinyApp(ui = ui, server = server)
```

**Comment by happyshows** [comment]
@timelyportfolio Now it works! Could you highlight the diff with the master in some R Doc. I'd like to incorporate your codes to my customized version soon.

**Comment by timelyportfolio** [comment]
Not sure if this helps, but you could look at https://github.com/timelyportfolio/networkD3/compare/feature/zoom-force for a diff.

**Comment by happyshows** [comment]
@timelyportfolio thanks, I figured the diff piece out.

Also, although it's a bit out of your buildingwidget scope, could you create a minimal shiny example on downloading a rendered SVG/d3 graph through clicking a button?
My previous attempts all failed :(

**Comment by christophergandrud** [comment]
@timelyportfolio This looks good. Please submit a pull request when you feel ready.

**Comment by christophergandrud** [comment]
Added with c33a24eeac6c0b9e410531769c72ef8f4c019ee3
