### ISSUE TITLE
sankeyNetwork requires 0-indexed id's

### ISSUE THREAD

**Issue by swiftsam** [christophergandrud/networkD3#101]
I noticed today that when an `id` column is explicitly provided for the `nodes` object, it must be 0-indexed.  When the id's start at 1, the plot fails to render and produces the following javascript error

```
Uncaught TypeError: Cannot read property 'sourceLinks' of undefined
```

from line 117 of sankey.js
```js
source.sourceLinks.push(link);
```

This should be reproducible with 

1. original example with no `nodes$id` column :sunglasses: 
1. modified with 0-indexed `nodes$id` column :sunglasses: 
1. modified with 1-indexed `nodes$id` column :x: 

```R
library(networkD3)

# get data for standard example
URL <- paste0(
  "https://cdn.rawgit.com/christophergandrud/networkD3/",
  "master/JSONdata/energy.json")
Energy <- jsonlite::fromJSON(URL)

# extract link and node objects
links <- Energy$links
nodes <- Energy$nodes

## 1
# Plot with original objects works fine
sankeyNetwork(Links = links, Nodes = nodes, Source = "source",
              Target = "target", Value = "value", NodeID = "name",
              units = "TWh", fontSize = 12, nodeWidth = 30)

## 2
# explicitly add 0-indexed ids to nodes object
nodes$id     <- 0:(nrow(nodes)-1)

# Plot with 0-indexed ids works fine
sankeyNetwork(Links = links, Nodes = nodes, Source = "source",
              Target = "target", Value = "value", NodeID = "name",
              units = "TWh", fontSize = 12, nodeWidth = 30)

## 3
# switch to 1-indexed ids
nodes$id     <- 1:nrow(nodes)
links$source <- links$source + 1
links$target <- links$target + 1

# Plot fails to render with Javascript error
sankeyNetwork(Links = links, Nodes = nodes, Source = "source",
              Target = "target", Value = "value", NodeID = "name",
              units = "TWh", fontSize = 12, nodeWidth = 30)


```

using networkD3 version 0.2.9

**Comment by christophergandrud** [comment]
Yep, that's because javascript is 0 rather than 1 indexed (like R). This is a constant irritation, but fundamental to using javascript for the visualisations.

**Comment by swiftsam** [comment]
I understand if it doesn't make sense to handle the mis-match in code, but it would have been super helpful to me if the  "Must be 0-indexed" to the argument description here
https://github.com/christophergandrud/networkD3/blob/master/R/sankeyNetwork.R#L17

**Comment by christophergandrud** [comment]
Good idea, thanks. Added (
https://github.com/christophergandrud/networkD3/commit/36a1f87540095096a4857790191164ae060c87d6
)

**Comment by swiftsam** [comment]
:+1: thanks for the package that makes my bosses think I'm some sort of wizard

**Comment by christophergandrud** [comment]
Ha! Thanks for reporting this issue.
