### ISSUE TITLE
Feature req: onClick event highlighting network neighbours

### ISSUE THREAD

**Issue by mexindian** [christophergandrud/networkD3#103]
In dense networks, it can be difficult to find relationships even after identifying our desired node. Would it be possible to provide a boolean input EXPAND that if true would make the onclick event highlight all neighbours as well.?

**Comment by cjyetman** [comment]
assume you're talking about in force network plots? see #168... we're working on focusing on related nodes and links on hover (sorry, not on click)

**Comment by mexindian** [comment]
I can't test because the dependant package relies on "digest" which is not available for 3.3.2... but from the description it looks good!

**Comment by cjyetman** [comment]
thanks... then closing this as a duplicate

**Comment by cjyetman** [comment]
btw... I have `digest` installed on R 3.3.2... maybe you should try installing `digest` first/separately?
```r
install.packages('digest')
```
[digest on CRAN](https://cran.r-project.org/package=digest)
