### ISSUE TITLE
Feature Req: Change Background color

### ISSUE THREAD

**Issue by JohnCoene** [christophergandrud/networkD3#106]
I don't currently see a way to change the background, would be a great addition :)

**Comment by cjyetman** [comment]
Setting the background color is not currently supported by `networkD3`, but can be achieved with the `htmltools` package. Credit to @timelyportfolio over on [stackoverflow](http://stackoverflow.com/a/36255290/4389763)

```r
library(networkD3)
library(htmltools)

data(MisLinks)
data(MisNodes)

browsable(
  tagList(
    forceNetwork(Links = MisLinks, Nodes = MisNodes,
                 Source = "source", Target = "target",
                 Value = "value", NodeID = "name",
                 Group = "group", opacity = 0.8),
    tags$script('document.body.style.backgroundColor = "#DAE3F9"')
  )
)
```
