### ISSUE TITLE
center of mass to center of screen

### ISSUE THREAD

**Issue by hxrts** [christophergandrud/networkD3#109]
The energetics of the graph plots often causes them to drift. Would be a nice feature to anchor them to center of screen.

**Comment by cjyetman** [comment]
you're talking about the force network plots I assume?

**Comment by hxrts** [comment]
yep, force plots.

**Comment by cjyetman** [comment]
I think this exact issue is being addressed in #176. There's a dev version noted in that thread that has a fix for this. Please check it out if you can and let us know if that resolves this issue. I'm going to close this issue now as a duplicate.
