### ISSUE TITLE
Export the JS code as plain text?

### ISSUE THREAD

**Issue by huyiqun** [christophergandrud/networkD3#112]
Is there functionality for this? I want to insert the generated d3 object into some other html or JS file. I tried to save it as html and looked into the source code, but it has super long random characters after `<script src="data:application/x-javascript;base64, KGZ1bmN0aW9uKCkg...`, two of these entries. Not sure if these are necessary or what alternative steps should be taken. Thanks!

**Comment by christophergandrud** [comment]
You can also use `selfcontained = FALSE` with `saveNetwork`. This will give you the raw javascript spread over multiple files.

**Comment by huyiqun** [comment]
Thanks, Chris!
