### ISSUE TITLE
feature request: static force network

### ISSUE THREAD

**Issue by marnilush** [christophergandrud/networkD3#115]
first of all: thanks a lot for the great work! There are two things, however that would make the
library even better and help me a lot (unfortunately, i don't know enough JavaScript to try
implementing that myself): 

I would like to be able to pass precomputed node x,y coordinates to the forceNetwork
function and generate a static representation of the network that is still zoomable but
the nodes would (ideally) not be draggable any more (or always snap back to their
fixed positions when the mouse is released). In addition, i would be great to have a
updateForceNetwork function that could be used to change parameters of the network
and redraw it (e.g. after changing the node colors etc.)

**Comment by cjyetman** [comment]
It's possible, and I think potentially a good option, to have D3 run the simulation before creating any of the SVG elements, and only drawing the SVG elements at their final location after *n* iterations of the simulation. Is that what you're looking for?

I don't think it's a very good idea to have the user precompute the positions themselves and then pass them to D3... that defeats the entire purpose of using D3's force simulation.

**Comment by marnilush** [comment]
Hi and sorry for my delayed reply. Yes, this is (in part) what i was
looking for and it would be great if you could include the
precomputation option.

cheers,
Marc

2017-03-16 13:10 GMT+01:00 CJ Yetman <notifications@github.com>:
