### ISSUE TITLE
NaN produced in 2-node/linear radial/diagonal Network

### ISSUE THREAD

**Issue by RohdeK** [christophergandrud/networkD3#116]
First off, thanks for this helpful package!

There is an issue with hierarchical lists with only singular connections when using radialNetwork or diagonalNetwork. 

Example R chunk:

diagonalNetwork(list(name = "a", children = list(list(name = "b"))))

This produces the attached output, which has no paths and overlapping nodes. This is also happening for multiple nodes, that are in one "line", i.e. each one level further down.

![example](https://cloud.githubusercontent.com/assets/19207114/15044282/e2a71772-12d3-11e6-9682-cdbe31490136.png)

Apparently, when arranging the nodes, there are NaN values produced, that don't get interpreted right. Is it possible to fix this misalignment? 

Best regards,
Konstantin

**Comment by christophergandrud** [comment]
Thanks for reporting this. It might take me awhile to get to this as I'm pretty busy with other projects at the moment.

**Comment by RohdeK** [comment]
After looking into the **.js** files, there is a simple fix, that seems to be sufficient. 

The error occurs in line 64 from **radialNetwork.js** and line 60 from **diagonalNetwork.js**, where the `separation` function is defined.
The function itself reads:
`function(a, b) {return (a.parent == b.parent ? 1 : 2) / a.depth ;}`

Apparently, (after some debugging), those "linear" graphs yield some nodes of zero `depth`. (Coherent with the observation that NaN are produced.)

In those lines, one can substitute `... / a.depth` with ` ... / Math.max(1, a.depth)`.

This obviously does not change the behaviour of the function in cases where everything was okay anyway. But "linear" graphs are now rendered correctly, for any number of nodes. 

Maybe you could include this in your next package version.
Greetings, 
Konstantin

**Comment by christophergandrud** [comment]
Great. Could you submit this as a pull request (so that you can get full
credit)?

**Comment by RohdeK** [comment]
I am not sure, if I did this right, but I tried to do the pull request. 
(I think, I accidentally did a pull request to my own repository first.)
