### ISSUE TITLE
Dynamically add names to nodes

### ISSUE THREAD

**Issue by hmaeda** [christophergandrud/networkD3#118]
Hi,

In my opinion the power of algorithmically/programmatically generated network graphs come from the human interaction to label parts of the graph, in particular, labelling nodes or edges.

Shiny offers some of this 'human interaction' so I was wondering.... in a shiny app, I would like the user to be able to dynamically add names to nodes/edges in a network graph, is this possible? And then once the nodes/edges names are added, if it the data and output can be saved for future use. If these are not currently possible, could this be added as a feature.

The human interaction provides additional data to the graph, which can be used for further analysis.

Regards,

HLM

**Comment by christophergandrud** [comment]
My off the top of my head thought is that you could probably write the shiny app to change the node labels in the data and then re-render the plot. The data could probably be written out. 

This would all be in shiny though, there is nothing inherent to networkD3 that would be involved in this.
