### ISSUE TITLE
Feature request: node shape parameter

### ISSUE THREAD

**Issue by smjenness** [christophergandrud/networkD3#12]
Thank you for this great package! I have a feature request to have function parameters for `forceNetwork` or `simpleNetwork` that control the size and shape of the nodes. One might want, for example, the color to be based on Group, the size to be based on another nodal attribute, and the shape to be based on a third. Thank you.

**Comment by koundy** [comment]
Hi, Great work ! I have a question. Can i Change size of the nodes according to a numeric variable?

**Comment by cjyetman** [comment]
changing the title because `Nodesize` is already an available argument in `forceNetwork()`
