### ISSUE TITLE
edge colors

### ISSUE THREAD

**Issue by umerijaz** [christophergandrud/networkD3#121]
Hi, 

I am wondering if it is possible to color the edges separately in the forceNetwork and sankeyNetwork functions by referring to a column in the attached dataframes? At the moment all the edges have the same colors. The reason I am asking this is that I am drawing correlation networks where I want to show positive correlations as blue and negative correlations as red.

Best Wishes,
Umer

**Comment by cjyetman** [comment]
`forceNetwork()` has a `linkcolour` argument, which I'm almost certain provides the functionality you're asking for. try this with the latest version of networkD3 (currently 0.3)
```r
library(networkD3)

URL <- paste0("https://cdn.rawgit.com/christophergandrud/networkD3/",
              "master/JSONdata/miserables.json")
MisJson <- jsonlite::fromJSON(URL)
ValjeanInds <- which(MisJson$links == 11, arr = TRUE)[, 1]
ValjeanCols <- ifelse(1:nrow(MisJson$links) %in% ValjeanInds, "#bf3eff", "#666")

forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source", Target = "target", 
             Value = "value", NodeID = "name", Group = "group", opacity = 0.8, 
             linkColour = ValjeanCols)
```

is this relevant for sankey plots?
