### ISSUE TITLE
sankeyNetwork resize/refresh does not work

### ISSUE THREAD

**Issue by fbreitwieser** [christophergandrud/networkD3#122]
First, thanks for this great package.

I include a Sankey network in my program which is updated based on user input. However, it resizes and zooms into the network with the updates, instead of showing the full network. I found that when I comment out the viewBox code in sankeyNetwork.js, and un-comment the resize function code, it works as expected (though it re-draws the Sankey).

**Comment by mcharles** [comment]
I also have an issue with resizing of Sankey networks (in the context of a htmlwidgets & R Flexdashboard). Any update on this issue? @fbreitwieser - is this the workaround you continue to use or have you found something else?
