### ISSUE TITLE
sankeyNetwork tooltip concatenates source and target name without whitespace

### ISSUE THREAD

**Issue by tts** [christophergandrud/networkD3#126]
As seen [in this example](http://tuijasonkkila.fi/migration.html) the text value of the title element is concatenated from source&target name without whitespace in between (also, newline is verbatim). The same happens with the example data of the sankeyNetwork function documentation, energy.json.

I've tried to get around this issue with the onRender function of htmlwidgets, [used here in another case](http://stackoverflow.com/questions/35215306/place-text-values-to-right-of-sankey-diagram) but without any luck so far. 

AFAIK the relevant lines in the code are within [173-175](https://github.com/christophergandrud/networkD3/blob/master/inst/htmlwidgets/sankeyNetwork.js#L173-L175).

**Comment by christophergandrud** [comment]
Hi @tts. Could you send a screenshot highlighting the issue (I'm having trouble seeing it, but it's probably just me).

**Comment by tts** [comment]
Hi @christophergandrud Sorry about the quality of the pic, had to take a photo of the screen but hopefully you can see what I mean. 
![sankey](https://cloud.githubusercontent.com/assets/309953/15814094/cf8e83d4-2bcc-11e6-8c1c-6c408b3b01e6.jpg)

**Comment by christophergandrud** [comment]
Ah thanks. (The tooltips don't show up in the linked version, at least on my browser). 

Given that this is HTML not R, they should really be concatenated using `<br>` not `\n`.

**Comment by christophergandrud** [comment]
Can you test out this dev branch:

```r
devtools::install_github('christophergandrud/networkD3', ref = 'tooltipCon')
```

to see if it solves the issue.

**Comment by tts** [comment]
Yes, that did it! 
![sankeytooltipok](https://cloud.githubusercontent.com/assets/309953/15860193/c9b1d57e-2cd0-11e6-84a0-658cd486b9a0.jpg)
Thanks, kind of you too look into this so promptly.

**Comment by christophergandrud** [comment]
Great. I've added the fix into the master branch (https://github.com/christophergandrud/networkD3/commit/5fa8f77e6808b15f42c730986999d9b8eac86a38) and it will be in the next CRAN release.
