### ISSUE TITLE
feature request: spatial node grouping by group membership?

### ISSUE THREAD

**Issue by ghonk** [christophergandrud/networkD3#13]
It would be really neat to be able to group nodes based on their group membership - possibly by having attraction for within group members and repulsion for non-group members - it would make this package ideal for designing neural net diagrams. thanks for the neat package.

**Comment by ghonk** [comment]
I got a chance to do a cursory search on this issue. Given more time, i'd like to dig in to see how I could integrate this [type of behavior](http://bl.ocks.org/mbostock/1021841), so any advice would be appreciated.

In my case, I'd like the nodes on [this site](http://bingweb.binghamton.edu/~ghonke1/) to be grouped together (ideally by group membership), so it consistently renders to look like a typical neural network (rather than occasionally as a ferris wheel-like structure).

**Comment by christophergandrud** [comment]
Sounds interesting. I'ld definitely look at a pull request.

**Comment by cjyetman** [comment]
Some rough equivalent of [this example that you gave](http://bingweb.binghamton.edu/%7Eghonke1/) should already be achievable if the links/edges are set appropriately, though I admit I don't really know what it means to "look like a typical neural network".
