### ISSUE TITLE
Bug: if Links data.frame is also a tbl_df, then LinkGroup doesn't work

### ISSUE THREAD

**Issue by mexindian** [christophergandrud/networkD3#138]
I was using dplyr with networkD3 and it took me ages to find this bug. it can be resolved by simply inserting this inside `sankeynetwork()`:

`if("tbl_df" %in% class(Links)){Links <- as.data.frame(Links)}`

**Comment by christophergandrud** [comment]
Thanks for the suggestion. I added it in at d549ce844f019be5cdce8c5c4787bd09ed250940. (Also added to `forceNetwork` and `simpleNetwork`).
