### ISSUE TITLE
Feature request: Phylogram with already written D3 code

### ISSUE THREAD

**Issue by apapanico** [christophergandrud/networkD3#14]
Hey,
I am doing a hierarchical clustering with a few hundred objects and I'm trying to find a nifty way to visualize the clustering and allow someone to play around with parameters and possibly zoom in and out.  I've just started looking into how to make a Phylogram and I think it might be a good addition to networkD3.  The following are examples of the d3 already implemented:
- https://gist.github.com/kueda/1036776/
- http://bl.ocks.org/kueda/1036776
- https://github.com/tim-thimmaiah/phylonator/tree/master/js (this nifty implementation features zoom)

I have literally zero experience with javascript and d3 so I have absolutely no idea what I'm doing.  I'm just trying to replicate what's been done already in networkD3 and patch in the stuff above.

The basic issues:
1. Considering that newick.js is already written, really it comes down to just passing the newick string.  In R, ape::write.tree does that to a phylo object.
2. Other than that, it's just piecing together the htmlwidgets components I guess.  I think I have the necessary .R file together but the .js file for htmlwidgets is harder for me to figure out.  For one, since the code for the phylogram is already written, it'd be nice to just call the functions but I just don't see how it's done.

With the js already written, how hard is it to get this up and running with the htmlwidgets?

**Comment by jjallaire** [comment]
@timelyportfolio and @christophergandrud, do you think this should be a new standalone htmlwidget or is it logically a part of networkD3?

**Comment by christophergandrud** [comment]
Thematically I think it makes sense. A phylogram is just a more linear representation of what `treeNetwork` does.

**Comment by abresler** [comment]
This will be great, can't wait.  Also want to see if there is an
interactive library that could fit visualizing topological data algos like
SOM and Kohonen

-- 
Alex Bresler

ASBC LLLC
asbcllc.com
917-455-0239

abresler@asbcllc.com
@abresler

**Comment by timelyportfolio** [comment]
@christophergandrud @jjallaire I have spent quite a bit of time trying to determine some guidelines or best practices for this, especially considering at the end of the year, I could have > 52 widgets.  Some early thoughts I had regarding packaging widgets involved similarities in :

1. type of visualization
2. field of study
3. similar Javascript dependencies
4. symbiotic features
5. type of parameters/inputs, such as `diagram` in `DiagrammeR` for both `mermaid` and `graphviz`

**Comment by abresler** [comment]
God 2015 is going to be amazing for R

-- 
Alex Bresler

ASBC LLLC
asbcllc.com
917-455-0239

abresler@asbcllc.com
@abresler

**Comment by christophergandrud** [comment]
@timelyportfolio That is a really nice framework for thinking about this. Thanks for spelling it out.

I'm completely happy with you giving this a shot.

**Comment by timelyportfolio** [comment]
ok, maybe I'll make it next week's widget http://buildingwidgets.com :)

**Comment by christophergandrud** [comment]
:+1:

**Comment by timelyportfolio** [comment]
You can test, spectate, help, track progress in this [branch](https://github.com/timelyportfolio/networkD3/tree/feature/phylogram).  I went with the d3.phylonator.js, but it is buggy due to new `d3` behavior and with some of its events.  I worked through most to get a very rough first draft.

**Comment by timelyportfolio** [comment]
before I forget, I wanted to add this http://www.jsphylosvg.com/ as another possible library for producing these

**Comment by timelyportfolio** [comment]
also, should definitely work integrate with the `ape` package and see this book http://ape-package.ird.fr/APER.html

**Comment by timelyportfolio** [comment]
As I work through this, it seems better to work on a tree network and dendrogram to be more generic than a phylogram, since this does not currently exist within `networkD3`.  @christophergandrud, you ok with this?

**Comment by christophergandrud** [comment]
Sounds reasonable to me.

**Comment by timelyportfolio** [comment]
Ok, I built an ugly implementation with examples [here](http://bl.ocks.org/timelyportfolio/raw/59acc3853b02e47e0dfc/) and [code](http://gist.github.com/59acc3853b02e47e0dfc/).  @christophergandrud and @apapanico, any opinions on this?  The `phylogram` code to me looks much nicer but lacks the pan/zoom and hover interactivity of `phylonator`.  Collapsible is missing in both, but shouldn't be that hard to implement. 

[`jsPhyloSVG`](http://www.jsphylosvg.com/documentation.php) is also pretty with minimal interactivity, but seems to have been abandoned.  I think it might be used as an example for multiple formats and tests.

**Comment by apapanico** [comment]
@timelyportfolio Looks rad to me.    Also, I get the sense a Phylogram just a term for a Dendrogram used in a certain fields?  I guess the crux of it was that the classic js dendrograms didn't have a branch length parameter and this phylogram implementation did.  And of course in hierarchical clustering, the branch length is an important component of the visualization.

Cool to see the (very simple) phyloNetwork.js code.  I need to compare with what I had tried.

**Comment by timelyportfolio** [comment]
well, before comparing, let me get it in respectable format :)  Certainly don't want to propagate bad practice.

**Comment by timelyportfolio** [comment]
I think I'll now start on a generic dendrogram/tree and circle back to the phylogram special case.

**Comment by timelyportfolio** [comment]
@christophergandrud it seems `treeNetwork` could be modified to build more tree layouts than `Reingold-Tilford Tree`.  Would this be ok, or would you rather other layouts be in a separate function than `treeNetwork`?

**Comment by timelyportfolio** [comment]
while on the topic of dendrograms, I also thought it interesting that I discovered `dendextend` has a non-exported [`d3dendrogram`](https://github.com/talgalili/dendextend/blob/master/R/d3dendrogram.R#L20-L96) feature.

**Comment by cjyetman** [comment]
Would using `diagonalNetwork()` if it had an argument like `linkType = "elbow"` as in `dendroNetwork()` achieve the desired result? If so, completion of #171 will probably be a sufficient substitute.

**Comment by cjyetman** [comment]
this can be roughly achieved with the new treeNetwork function...
```r
data <- read.csv(header = T, stringsAsFactors = F, text = '
nodeId,parentId,name,height
0,,,0
1,0,,0.00555
2,1,,0.04732
3,2,Crotalus_oreganus_oreganus_cytochrome_b,0.05532
4,2,Crotalus_horridus_cytochrome_b,0.10598
5,1,,0.06255
6,5,Thamnophis_elegans_terrestris_cytochrome_b,0.06621
7,5,Thamnophis_atratus_cytochrome_b,0.06427
8,0,,0.05762
9,8,Pituophis_catenifer_vertebralis_cytochrome_b,0.06314
10,8,Lampropeltis_getula_cytochrome_b,0.07797
11,0,,0.00779
12,11,Hypsiglena_torquata_cytochrome_b,0.06125
13,11,,0.01037
14,13,Diadophis_punctatus_cytochrome_b,0.07523
15,13,Contia_tenuis_cytochrome_b,0.06379
')
data$height <- 1 - data$height
treeNetwork(data, linkType = 'elbow', defaults = c(nodeStroke = 'yellowGreen', linkWidth = 3))
```

**Comment by cjyetman** [comment]
and as_treenetdf calculates height when converting hclust and ape::phylo objects... examples...
```r
library(ape)
tree <- ape::rtree(n = 20)
plot(tree, edge.width = 2)

library(networkD3)
treeNetwork(tree, linkType = 'elbow')
```
```r
hc <- stats::hclust(stats::dist(USArrests), "ave")

library(networkD3)
treeNetwork(hc, linkType = 'elbow')
```

**Comment by cjyetman** [comment]
I believe that the customizability of the new treeNetwork function enables sufficient replication of a phylogram through...
1. use of the node 'height' column in the 'native' treenetdf format
2. as_treenetdf() ability to calculate 'height' for ape::phylo and hclust objects during conversion
3. `linktype = 'elbow'` argument, and other possible customizations

Closing this issue as the overall concept is now possible. If there are specific bugs or improvements to be made, let's open new issues for them.
