### ISSUE TITLE
Sankey Diagram with R library networkD3 does not show colors

### ISSUE THREAD

**Issue by oli666** [christophergandrud/networkD3#141]
Hi, 
I do have the following issue (http://stackoverflow.com/questions/38724455/sankey-diagram-with-r-library-networkd3-does-not-show-colors): The code shows 4 examples of creating a Sankey diagram, only "Sankey4" works as designed, i.e., no colors: 

`
library(networkD3)
my_nodes = structure(list(name = c("HawaiTEST", "AMSVOASMPP01", "App1", 
                                   "Transfer", "Transferred_tel__63null_",
                                   "Transferred_tel__631100107_", 
                                   "AMSVOASMPP02",
                                   "Transferred_tel__631100108_",
                                   "Transferred_tel__631100106_", 
                                   "Transferred_tel__631100104_",
                                   "Transferred_tel__631100105_", 
                                   "FarEndDisconnect",
                                   "FarEndDisconnect_Hangup", "DutchAOS",
                                   "SwedenAOS", 
                                   "Transferred_tel__63000_")), class =
c("tbl_df", "tbl", "data.frame"
  ), row.names = c(NA, -16L), .Names = "name")
my_links = structure(list(key = c("0_1", "0_6", "1_13", "1_14", "1_2", "11_12", 
                                  "13_11", "13_3", "14_11", "14_3", "2_11",
                                  "2_3", "3_10", "3_15", 
                                  "3_4", "3_5", "3_7", "3_8", "3_9", "6_13",
                                  "6_2"), source = c(0L, 
                                  0L, 1L, 1L, 1L, 11L, 13L, 13L, 14L, 14L, 2L,
                                  2L, 3L, 3L, 3L, 
                                  3L, 3L, 3L, 3L, 6L, 6L), target = c(1L, 6L,
                                  13L, 14L, 2L, 12L, 
                                  11L, 3L, 11L, 3L, 11L, 3L, 10L, 15L, 4L, 5L,
                                  7L, 8L, 9L, 13L, 
                                  2L), total = c(38L, 36L, 4L, 3L, 31L, 6L, 2L,
                                  5L, 1L, 2L, 3L, 
                                  61L, 11L, 1L, 12L, 11L, 11L, 11L, 11L, 3L,
                                  33L)), class = c("tbl_df", 
                          "tbl", "data.frame"), row.names = c(NA, -21L), .Names
= c("key", 
    "source", "target", "total"))
sankey1 = sankeyNetwork(Links =my_links, Nodes = my_nodes, Source =
                           "source", Target = "target", Value = "total", units =
                           "calls", NodeID = "name")

sankey2 = sankeyNetwork(Links =my_links, Nodes = my_nodes, Source =
                           "source", Target = "target", Value = "total", units =
                           "calls", NodeGroup = "name")
sankey2
ColourScale <- 'd3.scale.ordinal()
            .domain(["lions", "tigers"])
           .range(["#FF6900", "#694489"]);'
sankey3 = sankeyNetwork(Links =my_links, Nodes = my_nodes, Source =
                           "source", Target = "target", Value = "total", units =
                           "calls", colourScale = JS(ColourScale))
sankey3
sankey4 = sankeyNetwork(Links =my_links, Nodes = my_nodes, Source =
                           "source", Target = "target", Value = "total", units =
                           "calls")
sankey4
`
"Sankey1" tries using "NoteID" the way it is used at the example from the web referenced above, however, doing that results in the diagram not being displayed at all; the same effect for "Sankey2". "Sankey4" is displayed in grey regardless of the color scheme definition.

I have also looked at the html code produced by both, my R code producing "Sankey1" as well as the code used on your web page. Obviously, there is a difference regarding the group: 
HTML from "Sankey1":

"group":{"name":["HawaiTEST", ...
...
"options":{"NodeID":1,"NodeGroup":"name","LinkGroup":null,

HTML excerpt from the web example:

"group":["Agricultural 'waste'","Bio-conversion", ...
...
"options":{"NodeID":"name","NodeGroup":"name","LinkGroup":null

Changing the output html for "Sankey1" in order to reflect the output from the web example solves the issue, "Sankey1" is displayed using the default color schema. 

Any help would be highly appreciated. 
Thanks
Oli

**Comment by timelyportfolio** [comment]
I answered on [StackOverflow](http://stackoverflow.com/questions/38724455/sankey-diagram-with-r-library-networkd3-does-not-show-colors/38741989#38741989).  Please let me know if the answer does not help solve your issue.

**Comment by oli666** [comment]
Closing that "issue" as indicated at [StackOverflow](http://stackoverflow.com/questions/38724455/sankey-diagram-with-r-library-networkd3-does-not-show-colors). Thanks for your help, appreciate it!
