### ISSUE TITLE
Attribute "NodeID" seems not to be working with library "dplyr" loaded

### ISSUE THREAD

**Issue by oli666** [christophergandrud/networkD3#142]
This issue relates to https://github.com/christophergandrud/networkD3/issues/141
However, I might have come across another explanation why I see the behavior as described. 

# Example that is working:

## SessionInfo Output:

_R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nvimcom_0.9-18

loaded via a namespace (and not attached):
[1] tools_3.3.0_

## R Code:

library(networkD3)
my_nodes = structure(list(name = c("HawaiTEST", "AMSVOASMPP01", "App1",
"Transfer", "Transferred_tel__63null_",
"Transferred_tel__631100107_",
"AMSVOASMPP02",
"Transferred_tel__631100108_",
"Transferred_tel__631100106_",
"Transferred_tel__631100104_",
"Transferred_tel__631100105_",
"FarEndDisconnect",
"FarEndDisconnect_Hangup", "DutchAOS",
"SwedenAOS",
"Transferred_tel__63000_")), class =
c("tbl_df", "tbl", "data.frame"
), row.names = c(NA, -16L), .Names = "name")
my_links = structure(list(key = c("0_1", "0_6", "1_13", "1_14", "1_2", "11_12",
"13_11", "13_3", "14_11", "14_3", "2_11",
"2_3", "3_10", "3_15",
"3_4", "3_5", "3_7", "3_8", "3_9", "6_13",
"6_2"), source = c(0L,
0L, 1L, 1L, 1L, 11L, 13L, 13L, 14L, 14L, 2L,
2L, 3L, 3L, 3L,
3L, 3L, 3L, 3L, 6L, 6L), target = c(1L, 6L,
13L, 14L, 2L, 12L,
11L, 3L, 11L, 3L, 11L, 3L, 10L, 15L, 4L, 5L,
7L, 8L, 9L, 13L,
2L), total = c(38L, 36L, 4L, 3L, 31L, 6L, 2L,
5L, 1L, 2L, 3L,
61L, 11L, 1L, 12L, 11L, 11L, 11L, 11L, 3L,
33L)), class = c("tbl_df",
"tbl", "data.frame"), row.names = c(NA, -21L), .Names
= c("key",
"source", "target", "total"))
sankey1 = sankeyNetwork(Links =my_links, Nodes = my_nodes, Source =
"source", Target = "target", Value = "total", units =
"calls", NodeID = "name")
sankey1

## Result

This works as expected. The html code for the "group" is as follows: 

"group":["HawaiTEST'", ...
...
"options":{"NodeID":"name","NodeGroup":"name","LinkGroup":null

# Example that is NOT working:

Pls note that the only difference is the additional import of the library "dplyr" (A library I need in the full version of my code!) 

## R Code:

library(networkD3)
**library(dplyr)**
my_nodes = structure(list(name = c("HawaiTEST", "AMSVOASMPP01", "App1",
"Transfer", "Transferred_tel__63null_",
"Transferred_tel__631100107_",
"AMSVOASMPP02",
"Transferred_tel__631100108_",
"Transferred_tel__631100106_",
"Transferred_tel__631100104_",
"Transferred_tel__631100105_",
"FarEndDisconnect",
"FarEndDisconnect_Hangup", "DutchAOS",
"SwedenAOS",
"Transferred_tel__63000_")), class =
c("tbl_df", "tbl", "data.frame"
), row.names = c(NA, -16L), .Names = "name")
my_links = structure(list(key = c("0_1", "0_6", "1_13", "1_14", "1_2", "11_12",
"13_11", "13_3", "14_11", "14_3", "2_11",
"2_3", "3_10", "3_15",
"3_4", "3_5", "3_7", "3_8", "3_9", "6_13",
"6_2"), source = c(0L,
0L, 1L, 1L, 1L, 11L, 13L, 13L, 14L, 14L, 2L,
2L, 3L, 3L, 3L,
3L, 3L, 3L, 3L, 6L, 6L), target = c(1L, 6L,
13L, 14L, 2L, 12L,
11L, 3L, 11L, 3L, 11L, 3L, 10L, 15L, 4L, 5L,
7L, 8L, 9L, 13L,
2L), total = c(38L, 36L, 4L, 3L, 31L, 6L, 2L,
5L, 1L, 2L, 3L,
61L, 11L, 1L, 12L, 11L, 11L, 11L, 11L, 3L,
33L)), class = c("tbl_df",
"tbl", "data.frame"), row.names = c(NA, -21L), .Names
= c("key",
"source", "target", "total"))
sankey1 = sankeyNetwork(Links =my_links, Nodes = my_nodes, Source =
"source", Target = "target", Value = "total", units =
"calls", NodeID = "name")
sankey1

## Result 
Empty browser page. Resulting html code: 

"group":{"name":["HawaiTEST", ...
...
"options":{"NodeID":1,"NodeGroup":"name","LinkGroup":null,

## Session Info 

R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0      networkD3_0.2.12 nvimcom_0.9-18  

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.7 R6_2.1.2        assertthat_0.1  magrittr_1.5    DBI_0.4-1       htmltools_0.3.5
 [7] tools_3.3.0     igraph_1.0.1    yaml_2.1.13     tibble_1.1      Rcpp_0.12.6     jsonlite_1.0   
[13] digest_0.6.10  

# Things I have tried (and failed)
- Change the order of the library import
- Use "detach" and/or unloadNamespace before using the sankeyNetwork function

**Comment by christophergandrud** [comment]
Hi @oli666 

This issue should be solved in the most recent development version (version 0.2.13) which you can download with `devtools::install_github('christophergandrud/networkD3')`. I should also have it on CRAN soon.

**Comment by oli666** [comment]
Thanks, this update solved the issue! For my example, it prints out the message: 
Links is a tbl_df. Converting to a plain data frame.
Nodes is a tbl_df. Converting to a plain data frame.

**Comment by christophergandrud** [comment]
Yep, that's just an background information message. (networkD3 doesn't actually accept `tbl_df`, the newest version just automatically converts them to R data frames rather than failing quietly.)
