### ISSUE TITLE
default font

### ISSUE THREAD

**Issue by ijlyttle** [christophergandrud/networkD3#15]
Hello,

Really digging networkD3 (getting into htmlwidgets is one of my new-year's resolutions).

Considering Sankey diagrams, but I think this may apply to the others, I see that the font family is hard-coded.

For example: 
https://github.com/christophergandrud/networkD3/blob/master/inst/htmlwidgets/sankeyNetwork.js#L121
(wrong link before)

Would you consider removing the `serif` specification, so that the browser (or css) could be used to specify the font?

Happy to make a PR, if you like.

Thanks,

Ian

**Comment by timelyportfolio** [comment]
@ijlyttle ok to close this now?

**Comment by ijlyttle** [comment]
Cool! Happy to close myself.

Thanks!
