### ISSUE TITLE
sankey: any way to force the order of nodes?

### ISSUE THREAD

**Issue by daattali** [christophergandrud/networkD3#153]
When creating a sankey network, sometimes it's useful to be able to have the nodes in a specific order, and there doesn't seem to be a good way of knowing what order they'll appear in.

Example:

```
links <- data.frame(source = c(0, 1, 0, 1), target = c(2, 2, 3, 3), value = c(1, 2, 3, 4))
nodes <- data.frame(name = c("a", "b", "c", "d"))
networkD3::sankeyNetwork(links, nodes, 'source', 'target', 'value', 'name')
```

(`a` is above `b`)

vs

```
links <- data.frame(source = c(0, 1, 0, 1), target = c(2, 2, 3, 3), value = c(1, 5, 3, 4))
nodes <- data.frame(name = c("a", "b", "c", "d"))
networkD3::sankeyNetwork(links, nodes, 'source', 'target', 'value', 'name')
```

(the only difference is that the value "2" changed to "5" and now `b` is above `a`)

**Comment by cjyetman** [comment]
If you set `iterations = 0` in `sankeyNetwork()`, you will effectively disable the algorithm which automatically determines the node placement (which is the primary purpose of the `sankeyNetwork()` function), and the nodes will be placed in the order that they appear in the `Nodes` dataframe.
