### ISSUE TITLE
Any way to export sankey plot as image programatically?

### ISSUE THREAD

**Issue by daattali** [christophergandrud/networkD3#155]
I want to include a sankey network in a shiny app, and provide a "download image" button. Is there any way to do this other than using's Winston's webshot pkg?

**Comment by fbreitwieser** [comment]
@timelyportfolio 's exportwidget might do what you want: https://github.com/timelyportfolio/exportwidget

**Comment by daattali** [comment]
Update: @timelyportfolio recently updated `exportwidget` so that now it does indeed work with sankey plots
