### ISSUE TITLE
Feature request: Vertical diagonal network with different node colors

### ISSUE THREAD

**Issue by KarthiAru** [christophergandrud/networkD3#163]
Something like this:
https://github.com/drbunsen/tool-tree-viz

Would this be possible using this package from R?

**Comment by christophergandrud** [comment]
You could do it with a horizontal orientation: http://christophergandrud.github.io/networkD3/#radial

**Comment by cjyetman** [comment]
this is the closest to what you want that `networkD3` can do for you at the moment...
```r
URL <- 'https://raw.githubusercontent.com/drbunsen/tool-tree-viz/master/tools.json'
data <- jsonlite::fromJSON(URL, simplifyDataFrame = FALSE)
networkD3::diagonalNetwork(data, nodeColour = 'red', nodeStroke = 'red')
```

trying to do this with `diagonalNetwork()`...
1. produces a "tidy" tree in which the ["depth of nodes is computed by distance from the root, leading to a ragged appearance"](https://bl.ocks.org/mbostock/4339184) (not what you're looking for)
2. doesn't allow for coloring nodes by group... you can only choose one node color
3. doesn't allow for vertical orientation

with `dendroNetwork()`...
1. creates tree graph where all the leaf nodes are at the same depth (what you want)
2. allows for vertical orientation
3. allows for passing a vector for `textColour`, which could be used to color the text according to the group of the node

however...
1. doesn't allow for coloring nodes by group... you can only choose one node color
2. is designed to work with `hclust` objects, which would be rather difficult to create specifically to represent the type of graph data you have
