### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by maxconway** [christophergandrud/networkD3#165]
On http://christophergandrud.github.io/networkD3/, you have the url for the flare data as ending ""master/JSONdata//flare.json". I believe it should be "master/JSONdata/flare.json" (one forward slash)

**Comment by cjyetman** [comment]
fixed the typo with #166 

However, you may be having some other problem, because the typo should not cause the code to not work. For instance, this works for me...
```r
URL <- paste0(
  "https://cdn.rawgit.com/christophergandrud/networkD3/",
  "master/JSONdata//flare.json")
Flare <- jsonlite::fromJSON(URL, simplifyDataFrame = FALSE)

URL <- paste0(
  "https://cdn.rawgit.com/christophergandrud/networkD3/",
  "master/JSONdata/flare.json")
Flare1 <- jsonlite::fromJSON(URL, simplifyDataFrame = FALSE)

identical(Flare, Flare1)
```
