### ISSUE TITLE
create release tags in the future

### ISSUE THREAD

**Issue by cjyetman** [christophergandrud/networkD3#169]
I think it would be helpful to create release tags in the future. Then you can easily install a previous version, which could be useful for testing, using something like...
```r
devtools::install_github('christophergandrud/networkD3', ref = 'v0.3.2')
```

Github's info on creating tags/releases is here: https://help.github.com/articles/creating-releases/

**Comment by cjyetman** [comment]
just learned that you can also install any of the previous versions [archived on CRAN](https://cran.r-project.org/src/contrib/Archive/networkD3/) with...
```r
devtools::install_version('networkD3', version = '0.2.13', repos = 'http://cran.us.r-project.org')
```
but I still think the release tags here in Github would be nice.

**Comment by christophergandrud** [comment]
I don't have a strong preference for this. But have found that the CRAN archived versions tends to be a good way to install previous versions that you know have been through CRAN check and are consistent.

**Comment by timelyportfolio** [comment]
I strongly favor Github tags in addition to CRAN especially since the required extra effort is minimal.
