### ISSUE TITLE
explore hierarchical reusable d3.charts for multiple layouts and behaviors

### ISSUE THREAD

**Issue by timelyportfolio** [christophergandrud/networkD3#17]
This project [`d3.chart.layout`](https://github.com/bansaghi/d3.chart.layout) provides nearly all the hierarchical layouts of d3 with the reusability of [`d3.chart`](https://github.com/misoproject/d3.chart) and nice built-in zoom and collapse.  It seemed to be much better than hand-building each of these layouts, so I started to explore in this [branch `feature/d3.chart.layout`](https://github.com/timelyportfolio/networkD3/tree/feature/d3.chart.layout) and added function `hierNetwork` to access these.  Here is a [demo](http://bl.ocks.org/timelyportfolio/raw/792d58792f558278a84b/) using a `hclust` and `flare.json` and the code to reproduce is in this [gist](http://gist.github.com/792d58792f558278a84b) (thanks gistr).

Before I flesh it out, I wanted to make sure that it would be deemed an acceptable addition.  @jjallaire & @christophergandrud , what do you think?

**Comment by jjallaire** [comment]
Sounds quite reasonable to me.

**Comment by christophergandrud** [comment]
This looks like something that definitely is worth exploring.

@timelyportfolio would it make sense to add you as a collaborator on this repo?

**Comment by timelyportfolio** [comment]
That sounds like responsibility :).  This is widget a week project seems like it will be exponentially overbearing, so might be better just to do random pull request method if ok with you.  I'll feature the `hierNetwork` functionality on the blog as the widget of the week.  I know it is premature, since I haven't even submitted a pull request.  Hope it does not cause any trouble.  Maybe it will attract some testers (doubt it).

**Comment by christophergandrud** [comment]
That's fine with me too. I'm looking forward to the post/pull request.

**Comment by timelyportfolio** [comment]
@christophergandrud, know you are really busy.  Happy now to be collab on repo, but just want to make sure I am aligned with vision/roadmap.

**Comment by christophergandrud** [comment]
That would be great. As you probably noticed I am totally swamped at the moment and don't really have much time to review pull requests/add features. 

Two of my main (previously unstated) guiding principles for the package are that it be simple and stable.

- **Simple**: the package should make intelligent (and opinionated) choices about what capabilities it gives users with an eye to keeping the syntax relatively simple. This gives the package a real advantage over using straight JS.

- **Stable**: the syntax should be relatively stable over time and output should be stable. I.e. it should be hard or impossible to make plots that are buggy.

**Comment by timelyportfolio** [comment]
Ok, I'm ready if you are.  I can start by just test/evaluating all the open pulls.

**Comment by christophergandrud** [comment]
Great. I just added you as a collaborator. Feel free to also add yourself as a author on the package Description.

**Comment by timelyportfolio** [comment]
Alright, I'll start with `sankeyNetwork` and try not to mess anything up and stay consistent to the principles.  Please let me know if I sway.

**Comment by christophergandrud** [comment]
Sounds good.

**Comment by rajshah4** [comment]
Hoping this issue is still going and we can get hierNetwork added to networkD3, the [demos at i saw](http://www.buildingwidgets.com/blog/2015/1/23/week-03-more-network-layouts) looked really good. Thanks

**Comment by cjyetman** [comment]
Just noticed this issue/thread after having started [#171 add a hierarchyNetwork() function](https://github.com/christophergandrud/networkD3/issues/171).

This is going to happen, but probably **not** using `d3.chart.layout`, so that we don't become dependent on yet another external project that seems to have gone dead (like the external sankey project).
