### ISSUE TITLE
add a treeNetwork() function

### ISSUE THREAD

**Issue by cjyetman** [christophergandrud/networkD3#171]
I propose adding a `hierarchyNetwork()` function which would be able to produce results from all three of the `dendroNetwork()`, `diagonalNetwork()`, and `radialNetwork()` functions.

All three of the `dendroNetwork()`, `diagonalNetwork()`, and `radialNetwork()` functions produce similar, hierarchical network plots, with only minor aesthetic differences. A `hierarchyNetwork()` function could achieve the same results of all three with just two arguments: `orientation = c('horizontal', 'vertical', 'radial')` and `type = c('dendro', 'tidy')`. Additionally, it seems feasible to write code that will check the class and attributes of an incoming data value/object and adapt it to a universally useable object to pass to the JavaScript, e.g. if it's an `hclust` then convert it to a list first, or if it's a `igraph`, run it through `igraph_to_networkD3()` first, etc.

In D3.js parlance...
- [cluster layouts (dendrogram)](https://github.com/d3/d3-hierarchy#cluster) are "node-link diagrams that place leaf nodes of the tree at the same depth. Dendograms are typically less compact than tidy trees, but are useful when all the leaves should be at the same level, such as for hierarchical clustering or phylogenetic tree diagrams."
- [tree layouts (tidy)](https://github.com/d3/d3-hierarchy#tree) are "node-link diagrams of trees using the Reingold–Tilford “tidy” algorithm, improved to run in linear time by Buchheim et al. Tidy trees are typically more compact than dendograms."
- a radial layout is simply a modification of the underlying coordinate system of either a dendrogram or a tidy-tree... similar to making a dendrogram or a tidy-tree either horizontal or vertical

At least in the case between dendrogram and tidy-tree, the underlying JavaScript code will possibly be different enough to warrant keeping them separated, so `hierarchyNetwork()` could simply be an alias to the `dendroNetwork()`, `diagonalNetwork()`, and `radialNetwork()` functions, switching depending on the arguments `type` and `orientation`. Ideally though, I think it would be better to try and combine all three into one JavaScript to reduce the development burden of managing three separate but similar functions, and then make `dendroNetwork()`, `diagonalNetwork()`, and `radialNetwork()` aliases of the new `hierarchyNetwork()` to maintain backward compatibility.

I haven't even begun on this, other than putting some thought into it, because it would be a rather substantial change. Thoughts?

**Comment by christophergandrud** [comment]
Makes a ton of sense to me to do this. Would really cleanup the syntax. The legacy functions could then be wrappers of `hierarchyNetwork` with particular orientations.

**Comment by cjyetman** [comment]
Now I'm wondering if this should be `treeNetwork()` instead because there are other possible plots of hierarchical network data. Or, it could stay as `hierarchyNetwork()` and in the future additional plot types could be added, like tree map and/or circle packing? @christophergandrud what do you think is the best strategy?

**Comment by christophergandrud** [comment]
tree and hierarchy seem to be equivalent terms, so I don't think it really matters that much. Unless anyone disagrees with that assessment, `tree` is shorter and easier to spell so `treeNetwork` seems like a better name.

**Comment by cjyetman** [comment]
initial implementation in #200. will open new issues for ongoing development tasks for treeNetwork
