### ISSUE TITLE
Colour scales with d3.js v4+

### ISSUE THREAD

**Issue by christophergandrud** [christophergandrud/networkD3#172]
Colour scales in d3.js v4+ seem to have changed breaking the README example:

```r
library(networkD3)

# Load data
data(MisLinks)
data(MisNodes)

# Plot
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.4,
             colourScale = "d3.scale.category20b()")
```

**Comment by cjyetman** [comment]
The default is now `colourScale = JS("d3.scaleOrdinal(d3.schemeCategory20);"`. If you remove the `colourScale` argument from the example it will work. Or if you change the value of the `colourScale` argument to `JS("d3.scaleOrdinal(d3.schemeCategory20);"` it will work.

That has to be done... `d3.scale.category20b()` does not exist in D3 v4+.

**Comment by christophergandrud** [comment]
Nice. I updated the examples in f4da70ec5b420f729a9090bc47340bc170689dae
