### ISSUE TITLE
make the hierarchical network plots collapsible

### ISSUE THREAD

**Issue by cjyetman** [christophergandrud/networkD3#186]
this has been discussed before (e.g. [in #60](https://github.com/christophergandrud/networkD3/pull/60#issuecomment-120900653) and #17) and even experimented with in dev branches (e.g. @timelyportfolio's [d3.chart.layout](https://github.com/timelyportfolio/networkD3/tree/feature/d3.chart.layout)), but I think this can be achieved by simply adding the feature to the existing code rather than rolling in another JavaScript framework (d3.chart) without too much trouble.

**Comment by timelyportfolio** [comment]
would definitely not use `d3.chart.layout` or additional dependencies.  Simple enough to roll in existing code.

**Comment by cjyetman** [comment]
The new treeNetwork function (#171 and #200) is collapsible. As treeNetwork will likely supersede diagonalNetwork, dendroNetwork, and radialNetwork, it's unlikely we will add this feature to those older functions.
