### ISSUE TITLE
SankeyNetwork doesn't plot in the viewer

### ISSUE THREAD

**Issue by meneos** [christophergandrud/networkD3#220]
I create two data frames (nodes and links), enter the SankeyNetwork with the necesary expresions but nothing plots in the viewer and no error message is shown in the console. I tried with the Energy dataset example and it did work.

This is what I'm trying to plot:
`sankeyNetwork(Links = TRANSFER20D.26J_2, Nodes = nodes_, Source = "Source", Target = "Target", Value = "Value", NodeID = "Nodos", fontSize = 12, nodeWidth = 20, units = "", NodeGroup = "Nodos", sinksRight = TRUE, LinkGroup = "Target")`

**Comment by cjyetman** [comment]
It is not possible to help you without the data frames you are using and/or a [reproducible example](https://stackoverflow.com/a/5963610/4389763). Additionally, these GitHub issues are intended for bugs, feature requests, and intended improvements, not support requests. You may be better served at https://stackoverflow.com
