### ISSUE TITLE
treeNetwork function no more in networkD3 package 

### ISSUE THREAD

**Issue by DalilaR** [christophergandrud/networkD3#221]
What is the new name of treeNetwork function?  I've downloaded networkD3 0.4 version, and I found out that it doesn't have treeNetwork anymore.  Thank you for the prompt response, Dalila

**Comment by cjyetman** [comment]
`treeNetwork` was [deprecated in version 0.2 in August 2015](https://github.com/christophergandrud/networkD3/blob/master/NEWS.md#02)

however, it is making a come back in a future release version, and the current dev version already includes the new and much more flexible `treeNetwork`... we'd be happy to get feedback
