### ISSUE TITLE
change underlying graph in shiny?

### ISSUE THREAD

**Issue by stevepowell99** [christophergandrud/networkD3#23]
This is great work ... but I just wasted an evening thinking I could change the underlying graph in shiny using [shinytable](https://github.com/trestletech/shinyTable), which would be even greater - I thought I would be able to edit the nodes and edge information in a spreadsheet and see the graph change in real time but I have come to the conclusion it won't work, will it? All your examples don't change the underlying graph, only the presentation. Any ideas on how that might be possible?

**Comment by stevepowell99** [comment]
Just fixed it for myself: https://stevepowell.shinyapps.io/riverplot/. Thanks to your package! very flexible.

**Comment by christophergandrud** [comment]
:+1:
