### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'options.colourScale')

### ISSUE THREAD

**Issue by mikheyev** [christophergandrud/networkD3#232]
I am running into a puzzling problem with my network. It works fine in RStudio, but the html I generate with knitr doesn't load in any browser with the TypeError above.  You can see an example on [here](https://mikheyevlab.github.io/dsx-rnai/dsx-rnai.html#figure_s2_interactive_network_of_dsx-connected_genes).

**Comment by cjyetman** [comment]
I you're willing to take the time to make a [minimal reproducible example](https://stackoverflow.com/a/5963610/4389763), I'd be willing to take the time to investigate the problem for you.

**Comment by mikheyev** [comment]
As it turns out it is something internal to knitr. Deleting all the cached data fixes this problem. Thanks!
