### ISSUE TITLE
make accessible the identity of a clicked vertex

### ISSUE THREAD

**Issue by rcorty** [christophergandrud/networkD3#234]
I see that it is possible to work with the vertex identity in with javascript, as in https://github.com/christophergandrud/networkD3/blob/9c0a9c9ff32c53212d2d43e0ae3cc664137315e6/inst/examples/examples.R#L40-L45, 
but I would like to be able to return to R which vertex was clicked.  I could compute on that in R and print out information relevant to that vertex.

**Comment by cjyetman** [comment]
Please use a forum like StackOverflow for questions like this. This is meant for bugs and issues. 

You probably want to use the Shiny JavaScript function `Shiny.onInputChange`. See here for more: https://shiny.rstudio.com/articles/js-send-message.html
