### ISSUE TITLE
Directed Network Arrow Size

### ISSUE THREAD

**Issue by MaximilianLombardo** [christophergandrud/networkD3#247]
Is it possible to change the size of the arrow heads in a directed network or to make edges curved so that simple cycles can be visualized?

**Comment by cjyetman** [comment]
Assuming we're talking about `forceNetwork`... neither of those is a current feature.

The size of the arrow head is currently dynamically adapted based on the value of the link. It is therefore also related to the width of the line. Setting the size manually would likely cause problems then, by getting the line width and arrow size out of sync.

As far as curved edges... curves are much harder to deal with than lines in many different ways. It would also likely have a significant impact on the performance. I doubt that is something that will realistically be added.
