### ISSUE TITLE
Zoom feature for saveNetwork

### ISSUE THREAD

**Issue by MayaGans** [christophergandrud/networkD3#249]
Hi! Firstly I wanted to thank you for such a wonderful package; as a student new to network analyses it produces beautiful visualizations! 

When using the saveNetwork function it seems I've lost the ability to zoom in and out of the graph through scrolling/pinching. Is there some code/javascript I can include within the html file that will allow me to pinch (in example #196 in the shiny app this feature does seem to work)?? 

Thank you, again!

**Comment by cjyetman** [comment]
Can you provide a minimal reproducible example so we know we’re on the same page please?

**Comment by cjyetman** [comment]
Your first example is not reproducible because you did not provide `MyClickScript`.

Your second example is not reproducible either because you only included the HTML output, not the code used to create it.

**Comment by cjyetman** [comment]
The "minimal" in minimal reproducible example means that the dataset and the complexity of the example code has been reduced as much as possible while still demonstrating the problem. So I don't need your full dataset and your full project code, just enough to demonstrate the problem. If you can't or won't provide that, then I will have to create one myself to analyze the problem and test potential solutions... which just means that it will take longer before I find the time and motivation to do so. Also, please do not discount the effect of things like what is passed to the `clickAction` parameter... adding custom JavaScript into the mix most definitely can have an effect on the zooming function, which is also achieved through JavaScript.

**Comment by MayaGans** [comment]
I changed the scale parameter in forceNetwork and now I'm able to pan/zoom! Not sure that's an actual resolution to the issue but enough to make me happy
