### ISSUE TITLE
dendroNetwork linkColour option is not working

### ISSUE THREAD

**Issue by teshomem** [christophergandrud/networkD3#255]
Hi,

`hc <- hclust(dist(USArrests), "ave")`
`dendroNetwork(hc, height = 600, linkType = 'elbow', linkColour = 'red')`

Thanks

**Comment by cjyetman** [comment]
confirmed. Thanks for the report and reproducible example.

This was fixed in `diagonalNetwork` and `radialNetwork` with #107, but `dendroNetwork` was missed.

https://github.com/christophergandrud/networkD3/blob/master/inst/htmlwidgets/dendroNetwork.js#L107 should be changed from
```r
      .style("stroke", "#ccc") 
```
to
```r
     .style("stroke", x.options.linkColour)
```

**Comment by teshomem** [comment]
Thanks, how quickly can it be fixed?

**Comment by cjyetman** [comment]
That's dependent on the people who are willing, and have the necessary skill and knowledge to volunteer their time to do so.

**Comment by teshomem** [comment]
OK, thanks. This fix is not difficult. If i make the changes in my own branch, will you allow me to push it to your repo so that i will make the PR?

**Comment by cjyetman** [comment]
Yes, you may make a PR. Once a maintainer merges it, it will be available if you install the dev version of the package from Github. Getting it rolled into a release version submitted to CRAN is another story though.

**Comment by teshomem** [comment]
Thank you so much for the help.
