### ISSUE TITLE
Feature request: collapse or bundle nodes

### ISSUE THREAD

**Issue by tylerbhampton** [christophergandrud/networkD3#258]
I've seen this feature for d3.js. I'm wondering if you know of or could impliment this for networkD3? The ability to group nodes and ungroup them.
http://bl.ocks.org/GerHobbelt/3071239

**Comment by cjyetman** [comment]
Just to be clear, that is not a feature of d3.js, but a feature that some people have built-in to their custom visualizations based on d3.js.

I, and probably a few of the other maintainers/developers here, are aware of the possibility and the utility of this feature, but adding new significant features is not a high priority at the moment.

**Comment by TS404** [comment]
I can confirm this would be hugely useful as a general feature.
