### ISSUE TITLE
Use different data columns to derive linkWidth and linkDistance 

### ISSUE THREAD

**Issue by Jesse-Kerr** [christophergandrud/networkD3#263]
Thank you for this great library. I was wondering if it is possible to use different columns in your dataset for the linkDistance and the linkWidth? In the examples listed, it uses `JS("function(d) { return Math.sqrt(d.value); }").` But I would want to use value for linkWidth and another column for linkDistance, or vice versa. I imagine there is a Javascript way to do thus, but I am not very skilled in Javascript.

Thanks for the help!

**Comment by cjyetman** [comment]
answered on [StackOverflow here](https://stackoverflow.com/questions/57729631/use-different-columns-in-dataset-for-networkd3-linkdistance-and-linkwidth/57736820#57736820)
