### ISSUE TITLE
Replace Node with PNG

### ISSUE THREAD

**Issue by bkellman** [christophergandrud/networkD3#265]
Would it be possible to replace the nodes with PNGs? Perhaps raster objects?

**Comment by cjyetman** [comment]
It is possible in JavaScript/D3, but nor directly with this package.

**Comment by bkellman** [comment]
Terrific! Please pardon my unfamiliarity but I saw that the output network on ln 16/20:
```<script type="application/json" data-for="htmlwidget-5a0c8348763c3da03edb">{"x":{"links":{"source":[69,62,86,69,86,62,12,1,5,90,88,90,88,91,89,95,87,8,91,90,100,93,88,94,98,89```
is approximately a json. Is there a simle way I can modify this object to add the file names of some png objects?

**Comment by cjyetman** [comment]
no... modifying that data would not make the nodes change to images

**Comment by bkellman** [comment]
I'd really appreciate a pointer in the right direction. I'm pretty unfamiliar with d3

**Comment by cjyetman** [comment]
frankly, you will not be able to achieve it without substantial knowledge of D3
