### ISSUE TITLE
Customizing the label/text for each link in ForceNetwork output?

### ISSUE THREAD

**Issue by TS404** [christophergandrud/networkD3#271]
Would it be possible to show custom lablel text for both unhovered and hovered nodes? E.g. for a coauthor network, initials when unhovered, full names when hovered. I'm looking to use this package for visualising networks of COVID19 publications clustered by authors, topics and citations ([openVirus](https://github.com/petermr/openVirus/issues/40)).

(Related to #239 and #243)

**Comment by cjyetman** [comment]
Yes, but only by writing custom JavaScript code to make it work. That is not a built-in feature.

**Comment by TS404** [comment]
Thank you. On an unrelated note, just in case you've much experience with shinyapps, I've been having trouble deploying at networkd3 online:
- Website: https://ts404.shinyapps.io/topicnetwork
- Code: https://github.com/TS404/TopicNetwork
Any ideas appreciated (also [asked at stackoverflow](https://stackoverflow.com/questions/61301407/immediate-disconnect-from-server-in-shinyapps-local-working-no-errors-reported))!

**Comment by cjyetman** [comment]
here's an example of changing the node label text on `mouseover` and `mouseout`...

```r
library(networkD3)
library(htmlwidgets)

MisNodes$initials <- gsub('[[:lower:]]', '', MisNodes$name)

network <- 
  forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
               Target = "target", Value = "value", NodeID = "initials",
               Group = "group", opacity = 1, opacityNoHover = 1)

network$x$nodes$initials <- MisNodes$initials
network$x$nodes$fullname <- MisNodes$name

name_switch_js <- 
  "function(el, x) {
    var nodes = el.getElementsByClassName('node');
    
    [...nodes].map(node => node.addEventListener('mouseover', function(ev) {
        d3.select(ev.target.parentNode).select('text').text(d => d.fullname);
      }, false));
    
    [...nodes].map(node => node.addEventListener('mouseout', function(ev) {
        d3.select(ev.target.parentNode).select('text').text(d => d.initials);
      }, false));
  }
"

onRender(network, name_switch_js)
```

**Comment by TS404** [comment]
champion, thank you!
