### ISSUE TITLE
Pass info from D3 back to [R]

### ISSUE THREAD

**Issue by TS404** [christophergandrud/networkD3#272]
Could data be passed back from the visualisation to an object in [R]?

For example. on this simple shiny app I'd ideally like to be able to populate a list in [R] based on nodes that are clicked. Currently, I have to do it via a checkbox list and clicking the nodes just calls a basic 'alert("You clicked " + d.name);'.

(Also asked at [r2d3-I79](https://github.com/rstudio/r2d3/issues/79))

**Comment by cjyetman** [comment]
You'll need to look into [Shiny Reactivity](https://shiny.rstudio.com/articles/reactivity-overview.html), which is not part of this package.

Here is one [example](https://stackoverflow.com/a/45219835/4389763) of using Shiny Reactivity with a `networkD3` plot.

Also in general, lease provide a [minimal reproducible example](https://stackoverflow.com/a/5963610/4389763) when asking for support.

**Comment by cjyetman** [comment]
Also FYI, `networkD3` does not use `r2d3`, so they likely will not help you over there.

**Comment by TS404** [comment]
Ah, thank you! That makes sense. Doubly thank you for the MRD link. I'll aim to do so in future.
