### ISSUE TITLE
Would it be possible to include Edge Labels in the forceNetwork code?

### ISSUE THREAD

**Issue by bio-bean** [christophergandrud/networkD3#273]
I found some people who have implemented edge labels into their java code, and it would be really cool if that was also in the R package (for me, I tried and failed with java). ([one example](http://bl.ocks.org/fancellu/2c782394602a93921faff74e594d1bb1), [another example](http://bl.ocks.org/jhb/5955887))

I'm finding the R package for networkD3 really useful, thank you so much!

**Comment by cjyetman** [comment]
There is not a built-in feature for that. You would have to add your own custom JavaScript to achieve it.
