### ISSUE TITLE
move nodes by hand in network

### ISSUE THREAD

**Issue by annarizzibramucci** [christophergandrud/networkD3#274]
I would like to be able to pull the nodes of the network around to display the version I prefer and then be able to safe that exact version of the network as an image file, is that possible with networkD3?

Also could you please tell me how to correctly organise my network data to produce a network? Is there a tutorial you could direct me to?

Thanks so much
Cheers

**Comment by cjyetman** [comment]
In RStudio’s viewer, one can play around with the output and then export as an image. 

There are examples here https://christophergandrud.github.io/networkD3/ and in the help files. There are many tutorials and examples if you use Google.
