### ISSUE TITLE
For visualizations like diagonalNetwork with large networks is there a way to increase the spacing between the edges and nodes so that it is cleaner? Or would it require adjustments in the html file itself?

### ISSUE THREAD

**Issue by zrodriguez89** [christophergandrud/networkD3#275]
Here is an example.

<img width="802" alt="Example" src="https://user-images.githubusercontent.com/30937144/84548316-54436000-acd3-11ea-9c56-f85d102067e2.png">

I have played around with margin arguments, but those don't affect the actually plotting.

**Comment by cjyetman** [comment]
Make the window that it is in bigger and it will fill the space?

**Comment by zrodriguez89** [comment]
Okay so I originally was viewing it as one of many tabs in Safari. After making it a solo tab in Safari that fixed the issue. However, attempting to do the equivalent in Chrome there is still some overlapping happening.

I assume that's just the nature of working with different browsers? I was looking at resizing options for chrome like an extension or other solutions since it isn't a function of zooming.
