### ISSUE TITLE
Count in boxes instead of using tooltip in R

### ISSUE THREAD

**Issue by Fatjetaa** [christophergandrud/networkD3#279]
Is it possible to add the number of count in the flow instead of using the tooltip in R?

**Comment by cjyetman** [comment]
please provide a minimal reproducible example, or at the very least specify which function/plot you're talking about

**Comment by Fatjetaa** [comment]
I am talking about the sankeyNetwork() function.

sankeyNetwork(Links = links, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "n", NodeID = "name", 
              sinksRight=FALSE)

**Comment by cjyetman** [comment]
If I understand your question correctly, that is not a current feature, and to achieve it one would have to do substantial modification to the underlying JavaScript. New text elements would need to be generated, and they would need to placed appropriately according to the path, as well as auto-update their position when the path changes.

**Comment by Fatjetaa** [comment]
Okay, thankyou
