### ISSUE TITLE
Nodes Font Color

### ISSUE THREAD

**Issue by higor-gomes93** [christophergandrud/networkD3#287]
Hi! I'm having trouble with my nodes labels. Nodes and nodes labels have the same colors when using forceNetwork. This was addressed in this [issue ](https://github.com/christophergandrud/networkD3/issues/123#issue-155571071), but I couldn't solve my problem. Any thoughs on how to solve this?

**Comment by cjyetman** [comment]
This works for me...
```r
library(networkD3)
library(htmlwidgets)

net <- forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 1, fontSize = 24, 
             fontFamily = "helvetica", opacityNoHover = 1)

customJS <- 
  'function() { 
    d3.selectAll(".node text").attr("stroke-width", ".5px").attr("stroke", "#fff");
  }'

htmlwidgets::onRender(net, customJS)
```

can you provide a minimal reproducible example to demonstrate the problem you're having?

**Comment by higor-gomes93** [comment]
That really worked for me, cjyetman! Thank you very much. Any clues on how to change de text colour inside the customJS function?

**Comment by cjyetman** [comment]
I don't know for sure the attribute or CSS names and values off the top of my head, but you can add more commands like
```javascript
.attr("font-color", "blue"
```
or

```javascript
.style("font-color", "blue"
```
to the existing chain above

**Comment by gd047** [comment]
> ```r
> d3.selectAll(".node text").attr("stroke-width", ".5px").attr("stroke", "#fff");
> ```

Did you find out what is the command to change the font color?
