### ISSUE TITLE
forceNetwork gets laggy as number of nodes gets larger

### ISSUE THREAD

**Issue by ayeTown** [christophergandrud/networkD3#294]
Hi there,
I was wondering if there is a way of making the force network less laggy as the number of nodes increases? Tends to be pretty slow as I increase the number of nodes even to just 1,000.
Thanks for your help,
AT

**Comment by cjyetman** [comment]
Unfortunately not. More nodes means more work. It was not really designed to work with more than 1000 nodes because there's not many realistic ways to show 1000+ nodes on a normal size computer screen without overlapping.

**Comment by neon-ninja** [comment]
https://github.com/vasturiano/3d-force-graph might be of interest
