### ISSUE TITLE
"An error has occurred!" displayed after publish rshiny

### ISSUE THREAD

**Issue by gwonchan** [christophergandrud/networkD3#297]
Hi, This is Jason and I am a user of your networkD3 to plot my network! I really appreciate your amazing job!

I want to publish the network plot on rshinyapps.io for my project and I have an issue after publishing them.
When I run app, it is working fine like yours. but publishing is not working with the error msg below.

https://6jv0lq-jason-yoon.shinyapps.io/project.

Also server.r is here.
========
library(shiny)

#### UI ####

ui <- shinyUI(fluidPage(
  
  titlePanel("Shiny networkD3 "),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("opacity", "Opacity (not for Sankey)", 0.6, min = 0.1,
                  max = 1, step = .1)
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Simple Network", simpleNetworkOutput("simple")),
        tabPanel("Force Network", forceNetworkOutput("force"))
      )
    )
  )
))
========

ui.r is here.
===========
library(shiny)

#### UI ####

ui <- shinyUI(fluidPage(
  
  titlePanel("Shiny networkD3 "),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("opacity", "Opacity (not for Sankey)", 0.6, min = 0.1,
                  max = 1, step = .1)
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Simple Network", simpleNetworkOutput("simple")),
        tabPanel("Force Network", forceNetworkOutput("force"))
      )
    )
  )
))
========

**Comment by gwonchan** [comment]
my bad, just added library(networkD3) in server.r and working!

**Comment by cjyetman** [comment]
I would guess this has nothing to do with {networkD3} and has to do with your {shiny} code and/or the shiny server. I would not expect {networkD3} to completely error our the page like that. What happens when you run it locally? Does this work locally...

```r
library(shiny)
library(networkD3)

data(MisLinks)
data(MisNodes)

server <- shinyServer(function(input, output) {
  
  output$simple <- renderSimpleNetwork({
    src <- c("A", "A", "A", "A", "B", "B", "C", "C", "D")
    target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
    networkData <- data.frame(src, target)
    simpleNetwork(networkData, opacity = input$opacity)
  })
  
  output$force <- renderForceNetwork({
    forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
                 Target = "target", Value = "value", NodeID = "name",
                 Group = "group", opacity = input$opacity)
  })
})


ui <- shinyUI(fluidPage(
  
  titlePanel("Shiny networkD3 "),
  
  sidebarLayout(
    sidebarPanel(
      numericInput("opacity", "Opacity", 0.6, min = 0.1, max = 1, step = .1)
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Simple Network", simpleNetworkOutput("simple")),
        tabPanel("Force Network", forceNetworkOutput("force"))
      )
    )
  )
))

shinyApp(ui, server)
```

**Comment by gwonchan** [comment]
Hey, thank you for your response!

I have checked logs on rshinyapps.io and it says

2022-11-22T15:29:47.698659+00:00 shinyapps[7541695]: Warning: Error in
simpleNetworkOutput: could not find function "simpleNetworkOutput"


I just added library(networkD3) in server.r and no issues!

I am sorry to bother you and have a great thanksgiving!

Jason

*Gwonchan Jason Yoon, Ph.D*

*Engineer*

*Frisco, TX 75035*

*Tel: 617-417-4270*

*www.linkedin.com/in/jason-yoon-41754880*




2022년 11월 22일 (화) 오전 9:42, CJ Yetman ***@***.***>님이 작성:
