### ISSUE TITLE
Manually setting colors (RGB/HEX) for group values in a forceNetwork diagram

### ISSUE THREAD

**Issue by mvolar** [christophergandrud/networkD3#301]
Hello,

i just adore the package and use it to visualize a lot of data, 

however when trying to connect visualizations created by this plot and my other plots, often the limiting factor is that I just can't seem to get the color to match (i.e. ggplot2 colors to this plot) or something similar to discern the patterns. I have a relatively low number of groups (10ish) so manually inputting the colors shouldn't be a problem, I was wondering is there a straightforward way to put in my own colors for my grouping variables, either as a separate value in the dataframe or manually in the rendered html?

**Comment by cjyetman** [comment]
here's a reproducible example
``` r
library(networkD3)

links <- 
  read.csv(text = "
    source,target,value,color
    0,1,1,#F00
    0,2,1,#00F")

nodes <- 
  read.csv(text = "
    node_id,node_label,node_group
    0,Oranges,Orange_node
    1,Apples,Apple_node
    3,Pears,Pear_node")


forceNetwork(
  Links = links,
  Nodes = nodes,
  Source = "source",
  Target = "target",
  Value = "value",
  NodeID = "node_label",
  Group = "node_group",
  opacity = 1,
  opacityNoHover = 1,
  linkWidth = 4,
  fontSize = 18,
  colourScale = JS('d3.scaleOrdinal(["#FFA500", "#F00", "#90ee90"], ["Orange_node", "Apple_node", "Pear_node"]);'),
  linkColour = links$color
)
```

![](https://i.imgur.com/fG8Ajix.png)

**Comment by mvolar** [comment]
Thank you very much for the solution! And the quick response!

I have little experience with JS but this is so elegant.
