### ISSUE TITLE
How to programmatically save as PNG format？

### ISSUE THREAD

**Issue by Reborn-J** [christophergandrud/networkD3#303]
Is there a programmatic way to save as PNG format instead of saving from the R editor?

**Comment by cjyetman** [comment]
Not directly with functions from this package, but there are ways of exporting the HTML output and then reading that in and taking a snapshot of the output, e.g. with [webshot](https://github.com/wch/webshot) or [webshot2](https://github.com/rstudio/webshot2).

Keep in mind that this package produces *interactive HTML/JavaScript*, which does not translate perfectly into a static image, so some things you may want might not translate/export as you expect.

**Comment by Reborn-J** [comment]
> Not directly with functions from this package, but there are ways of exporting the HTML output and then reading that in and taking a snapshot of the output, e.g. with [webshot](https://github.com/wch/webshot) or [webshot2](https://github.com/rstudio/webshot2).
> 
> Keep in mind that this package produces _interactive HTML/JavaScript_, which does not translate perfectly into a static image, so some things you may want might not translate/export as you expect.

Thank you for your quick response ! I’m very grateful for your help.
