### ISSUE TITLE
Add option for colapsable node in dendro

### ISSUE THREAD

**Issue by RaphaelRibes** [christophergandrud/networkD3#304]
Hi ! First thing first, thank you a lot for your work it really is a fantastic library.

I wanted to propose a feature enhancement for the dendroNetwork function. Specifically, an option that allows users to click on intermediate nodes in a dendrogram, causing the node to collapse its subtree and re-render the graph with a terminal node in its place. If it's possible to implement it could be fantastic.

Thank you again for your amazing work!

**Comment by cjyetman** [comment]
FYI, this package/repo is effectively abandoned. The owner/maintainer has not had any activity here for a few years now. I was an active maintainer, but I don't have adequate permissions to make any changes here.

I did start building a modernized version of networkD3, which has not been released on CRAN or completely finished, but it does function and has many new features/abilities including what you're asking for here (if I understand your request correctly).
https://cjyetman.com/network.r2d3/

for instance, compare
```r
hc <- hclust(dist(USArrests), "ave")

networkD3::dendroNetwork(hc, height = 600)

# pak::pak("cjyetman/network.r2d3") # to install
network.r2d3::tree_explorer(hc)
```

**Comment by RaphaelRibes** [comment]
Wow, thank you so much !
