### ISSUE TITLE
Internet Explorer Restriction message - External sand alone HTML file

### ISSUE THREAD

**Issue by redsofa** [christophergandrud/networkD3#31]
Hello,

When generating standalone external HTML files and loading these in IE (Version 9) I get a warning about blocked content... " 

Internet Explorer restricted this webpage from running scripts or ActiveX controls.

Do you know what IE would find "dangerous" from the generated output ? 

Thanks.

**Comment by cjyetman** [comment]
The exported HTML files include JavaScript, which Windows by default considers dangerous and therefore blocks it. You can avoid this by changing your security settings, see [here](http://stackoverflow.com/a/7038775/4389763) for example/instructions.

Alternatively, we could add a ["Mark of the Web"](https://msdn.microsoft.com/en-us/library/ms537628(v=VS.85).aspx) to the exported HTML, but then we have to ensure that it's Windows encoded, and it only works if your security settings for the web are allow scripts by default. @christophergandrud do you think this is worth it (I don't)?

**Comment by christophergandrud** [comment]
agreed @cjyetman, unless anyone can make a strong case otherwise. In the meantime I'm closing this issue.
