### ISSUE TITLE
Generating custom on click handlers or extending a graph type ...

### ISSUE THREAD

**Issue by redsofa** [christophergandrud/networkD3#32]
Is this a way to create a graph that is a "sub-class" of an existing graph type ? Say we want to expand on the simpleNetwork to have our own handlers, is there a recommended way to do this?

Thanks

**Comment by redsofa** [comment]
https://github.com/ramnathv/htmlwidgets/blob/master/vignettes/htmlwidgets-advanced.Rmd

The Passing JavaScript Functions section of the htmlwidgets Advanced Topics documentation seems to have some hints as to how to do this  ?

**Comment by cjyetman** [comment]
the `forceNetwork()` function has the `clickAction` argument which is a "character string with a JavaScript expression to evaluate when a node is clicked"
