### ISSUE TITLE
Use radial or cartesian clusters

### ISSUE THREAD

**Issue by christophergandrud** [christophergandrud/networkD3#33]

**Comment by ksrinivs64** [comment]
Hi I really like the Cartesian layout for tree networks but by default it seems to do radial?  Is there a way to pass it a parameter to force a Cartesian layout?  I am not a UI person, and I don't know Javascript/D3 etc. so sorry if the question is naive.

**Comment by christophergandrud** [comment]
This capability is not available currently.

**Comment by timelyportfolio** [comment]
Related to #39

**Comment by christophergandrud** [comment]
Thanks for following up @timelyportfolio. I'ld be happy to merge a pull request. (I really need to get at the networkD3 pull requests)

**Comment by timelyportfolio** [comment]
Let me know if I can help.  I will submit a pull in just a second.

**Comment by christophergandrud** [comment]
Great. I'll look at it now.

**Comment by christophergandrud** [comment]
Hm, I think that one largely builds on the radial capabilities already available in `treeNetwork` (though much more extensive). I think the request is for a layout more like this: http://bl.ocks.org/mbostock/4339184

**Comment by timelyportfolio** [comment]
Ok that makes sense.  I need to circle back to the hierarchical layout experiments from earlier.

**Comment by christophergandrud** [comment]
Sounds good.

**Comment by timelyportfolio** [comment]
Seems like this is now covered by `diagonalNetwork` and `radialNetwork`.  Can we close?  Thanks.
