### ISSUE TITLE
Inconsistent parameter names across ...network functions

### ISSUE THREAD

**Issue by Hunter-Github** [christophergandrud/networkD3#34]
With `simpleNetwork` and `treeNetwork` font size is set by `fontSize`, for `sankeyNetwork` and `forceNetwork` it is `fontsize`. Not a dealbreaker, simply a coding inconvenience. Thanks for the great package, BTW.

**Comment by christophergandrud** [comment]
Thanks for spotting this. `fontSize` now used in all functions as of 488fb61b019a995fcc935ec8f62a12afb4a08cea.
