### ISSUE TITLE
Unable to vary linkDistance in network graph created using forceNetwork of networkD3

### ISSUE THREAD

**Issue by JVAdams** [christophergandrud/networkD3#37]
FYI.  I submitted this issue to stackoverflow.
http://stackoverflow.com/questions/30446519/unable-to-vary-linkdistance-in-network-graph-created-using-forcenetwork-of-netwo
I got an answer that suggested a bug in d3js.
http://stackoverflow.com/a/30448047/2140956
I have submitted this as an issue to d3js.
https://github.com/mbostock/d3/issues/2451

**Comment by JVAdams** [comment]
This issue was closed on **d3js**, https://github.com/mbostock/d3/issues/2451, *"Sorry, but this is not the right place to fix the problem. If you have a string that represents a function, and you want to eval that string to turn it into code, you should do it outside of the D3 API."*

**Comment by jjallaire** [comment]
You can use the htmlwidgets::JS function to mark a string as requiring
evaluation. Since evaluating a string literal just returns itself it's
harmless to do this for all strings that might contain a function (e.g.
linkDistance could be passed into JavaScript always adorned with JS).

**Comment by JVAdams** [comment]
Thanks for the tip, @jjallaire.  I made this modification to the code originally posted on [stackoverflow](http://stackoverflow.com/questions/30446519/unable-to-vary-linkdistance-in-network-graph-created-using-forcenetwork-of-netwo/30448047#30448047):

    library(htmlwidgets)
    forceNetwork(Links=links2, Nodes=nodes2, 
          Source="Source", Target="Target", Value="Value", 
          NodeID="ID", Group="Group",
          linkDistance=JS('function(d) {', 'return d.value;', '}'))

And it works!  I will post your solution there.  (If you want to submit an answer there, I will accept it.)

**Comment by jjallaire** [comment]
Okay, I just replied on SO.

J.J.

**Comment by JVAdams** [comment]
Excellent.  Thanks for your help.

**Comment by JVAdams** [comment]
I think I was too hasty in closing this issue.  I suggest that the help page for `forceNetwork` be changed for the argument `linkDistance`, so it's easy for others to vary the link length.  For instance, something like this:

**Or a JavaScript function, possibly to weight by Value. For example: `linkDistance = htmlwidgets::JS('function(d) {', 'return d.value * 10;', '}')`.**

**Comment by jjallaire** [comment]
The preferred way to address this would actually be for the forceNetwork
function to call JS internally on the  linkDistance parameter (and any
other parameters which which might include JavaScript). That way the user
of the function doesn't need to sweat explicit invocation of JS.

**Comment by christophergandrud** [comment]
The trickiest thing about this package is deciding what capabilities to constrain so that the package is manageable and easy to use and which ones to allow uses to take full advantage of the JS. 

Currently the logic on the link distance is to allow the user to set an fixed value, then the user can use JS if they want to do something more complicated 

(btw, thanks for pointing out the documentation issue, fixed in 13c98feafff08b6421cf73bd12249035ba120fd1. Version 0.1.7 now makes it a little easier to use arbitrary JS across the package.)

However, if changing the link distance by value is really common, I can see a case for doing this internally.
