### ISSUE TITLE
forceNetwork edges not displaying

### ISSUE THREAD

**Issue by ssridhar21** [christophergandrud/networkD3#38]
I just started working with forceNetwork plots in R (great library by the way!). I am having issues getting edges to render correctly. Nodes appear ok, but I don't see any edges. I was able to replicate the sample plot (MisLinks and MisNodes objects), but the plot with my edge and node files doesn't seem to work correctly. Here's the code I used to create the network plot:

forceNetwork(Links = mod.edges.d3, Nodes = mod.nodes.d3,
             Source = "source", Target = "target",
             Value = "value", NodeID = "name", linkColour = "black",
             Group = "group", opacity = 0.8)

and a sample of my edge and node files:

> head(mod.edges.d3)
>   source target value
> 1      1     29     5
> 2      1     37     4
> 3      1    126     2
> 4      1    126     3
> 5      2     16     3
> 6      2     20     3
> head(mod.nodes.d3)
>   name group
> 1  g_1     1
> 2  g_2     1
> 3  g_3     1
> 4  g_4     1
> 5  g_5     1
> 6  g_6     1

I wasn't sure how to start targets in my edge file at '0'. I can provide the full edge and node files as well. any insight you might have would be greatly appreciated.

Best,
Sri

**Comment by timelyportfolio** [comment]
This might be a dumb answer but could you just do

mod.edges.d3$source = mod.edges.d3$source-1
mod.edges.d3$target = mod.edges.d3$target - 1

to start at 0 as JavaScript does?

**Comment by gregmacfarlane** [comment]
It would be really lovely to not worry at all about indexing the row names. Why can the link table not use the same `name` attribute from the node table? So, why can't the `MisLinks` data frame be

    From     To       weight 
    Val Jean Cosette  5
    Val Jean Javert   10

This would also make plotting an `igraph` instance fairly trivial. See my (unsuccessful) efforts [here](https://github.com/gregmacfarlane/forceGraph).

**Comment by timelyportfolio** [comment]
I believe `get.data.frame` will be most helpful here.  Below is a quick example using `data(karate)` from `igraphdata`.

```r
library(networkD3)
library(igraph)
library(igraphdata)

data(karate)

gdf <- get.data.frame(karate, what="both")

links <- data.frame(
  "source" = match(gdf$edges$from,gdf$vertices$name) - 1
  ,"target" = match(gdf$edges$to,gdf$vertices$name) - 1
  ,"weight" = gdf$edges$weight
)

forceNetwork(
  Links = links
  ,Nodes = data.frame(
    id = 0:(nrow(gdf$vertices)-1)
    ,name = gdf$vertices$name
    ,faction = gdf$vertices$Faction
  )
  ,Source = "source"
  ,Target = "target"
  ,NodeID = "name"
  ,Group = "faction"
  ,Value = "weight"
  ,opacity =  0.4
)
```

You might also be interested in these examples with other network `htmlwidgets`.

http://bl.ocks.org/timelyportfolio/109a4dabf671cc37f201
http://bl.ocks.org/timelyportfolio/762aa11bb5def57dc27f
http://www.buildingwidgets.com/blog/2015/5/22/week-20-vivagraphjs-in-diagrammer

**Comment by cjyetman** [comment]
@ssridhar21 have you tried this with the most recent version (currently 0.3) of networkD3? I think might be less picky about the zero-indexing now... i.e. it gives a warning but still works. Can you verify? And if so, can we close this issue?

**Comment by cjyetman** [comment]
Pretty sure this is no longer issue, so closing. Please test with most recent version of networkD3 (0.3+) and reopen with a minimal reproducible example if it's still an issue.
