### ISSUE TITLE
radialNetwork function

### ISSUE THREAD

**Issue by timelyportfolio** [christophergandrud/networkD3#39]
I integrated a new function `radialNetwork` for use in `networkD3` as explained in this [post](http://www.buildingwidgets.com/blog/2015/5/28/week-21-radialnetwork).  Happy to submit pull after you have had time to look at it, or I can easily make it into a separate package.

**Comment by christophergandrud** [comment]
I really like this. But it seems like it adds a layer of complexity that is a bit out of step with the other networkD3 functions..

**Comment by timelyportfolio** [comment]
certainly fine, I'll close the pull and make it its own little `htmlwidget`. I do think that there is a need though for some additional interactivity helpers, but maybe not the full ui like in `radialNetwork`.

**Comment by christophergandrud** [comment]
Sounds good.
