### ISSUE TITLE
add TreeColors.js for better tree colors

### ISSUE THREAD

**Issue by timelyportfolio** [christophergandrud/networkD3#40]
One of our own from the rstats community (@mtennekes & @edwindj) did this fine research on treemap coloring presented at [visWeek 2014](https://vimeo.com/102604515) and implemented in the R pkg [treemap](https://github.com/mtennekes/treemap).  Based on this research, @e- made [TreeColors.js](https://github.com/e-/TreeColors.js).  Adding this to tree visualizations is as simple as 

including the `treecolors.min.js` in the `yaml` [lines](https://github.com/timelyportfolio/networkD3/blob/feature/radialNetwork/inst/htmlwidgets/radialNetwork.yaml#L10-L13)

apply colors similar to the layout like in [lines](https://github.com/timelyportfolio/networkD3/blob/feature/radialNetwork/inst/htmlwidgets/radialNetwork.js#L140-L145)
```
var additive = TreeColors("add") // could also be subtract
additive(root)  // add a color object (HCL) to all the nodes
```

then in the styling like in [lines](https://github.com/timelyportfolio/networkD3/blob/feature/radialNetwork/inst/htmlwidgets/radialNetwork.js#L218-L219)

```
d3.selectAll(".node circle")
  .style("fill", function(d){return d3.hcl(d.color.h,d.color.c,d.color.l)})
```

I think this is a really nice addition.  I guess the question in my mind is do we make this default behavior or do we make it an option with a helper function?

![image](https://cloud.githubusercontent.com/assets/837910/7867940/a467a196-053e-11e5-91eb-964af6e79829.png)

**Comment by voxnonecho** [comment]
I think this should be the default behaviour

**Comment by timelyportfolio** [comment]
Going to close this for now, since over a year old.  Will implement tree colors in other way in other htmlwidgets.  Please ping me if anyone wants to see this.
