### ISSUE TITLE
Package Bloat? A function to add group and link strength to a simpleNetwork edgelist?

### ISSUE THREAD

**Issue by hansthompson** [christophergandrud/networkD3#44]
I want write a function that could be used to take the edgelists for simpleNetwork and make it cool for forceNetwork. I've got a script so far:

    # Load package
    library(networkD3)
    
    # Create fake data
    src <- c("A", "A", "A", "A",
             "B", "B", "C", "C", "D")
    target <- c("B", "C", "D", "J",
                "E", "F", "G", "H", "I")
    networkData <- data.frame(src, target)
    
    #Data is organized for simpleNetwork()
    #simpleNetwork(networkData)
    
    #Assume a dataframe with a group for each node
    exampleNodes <- data.frame(node = LETTERS[1:10], group = c(1,1,1,1,2,2,2,3,3,4))
    
    networkData$src <- as.numeric(factor(networkData$src, levels(exampleNodes$node)))
    networkData$target <- as.numeric(factor(networkData$target, levels(exampleNodes$node)))
    
    exampleLinks <- cbind(networkData, link_strength = sample(1:3, 9, replace = T))
    
    #shows some
    forceNetwork(Links = exampleLinks[1:2,], Nodes = exampleNodes,
                 Source = "src", Target = "target", 
                 Value = "link_strength", NodeID = "node",
                 Group = "group", opacity = 0.8)
    
    #not all though
    forceNetwork(Links = exampleLinks, Nodes = exampleNodes,
                 Source = "src", Target = "target", 
                 Value = "link_strength", NodeID = "node",
                 Group = "group", opacity = 0.8)

Thoughts? Criticism?

**Comment by christophergandrud** [comment]
Hm, I think this is probably outside the scope of the package. Currently the package only has plotting functions, but not preprocessing functions.

**Comment by hansthompson** [comment]
Thanks Chris. I will publish this kind of wrapper function elsewhere when I finish.
