### ISSUE TITLE
Embedding simpleNetwork in Slidify deck

### ISSUE THREAD

**Issue by theRanalyst** [christophergandrud/networkD3#46]
I've tried a slew of different things and cannot get the simpleNetwork to render in a Slidify deck when using runDeck(). I have added "ext_widgets : {networkD3: [htmlwidgets]}", "ext_widgets : {networkD3: [htmlwidgets/lib]}", "ext_widgets : {networkD3: [htmlwidgets/lib/d3-3.5.2]}" and all combinations there of to my yaml. I have also added simpleNetwork to my widgets line. I've tried using slidifyUI with htmlOuput, simpleNetworkOutput, or tags$div(id='networkGraph' class='shiny-html-output simpleNetwork networkD3') in the mainPanel( ) section. Nothing seems to be working and I can't figure out why. How do you incorporate this package into a slidify deck?

Thanks in advance!

**Comment by christophergandrud** [comment]
Hm, I actually haven't tried this before. Perhaps the best place to ask is over at the [slidify repo](https://github.com/ramnathv/slidify). @ramnathv might be the best person to ask as he was key in the development of both slidify and htmlwidgets.

**Comment by theRanalyst** [comment]
@christophergandrud Thanks for getting back to me! I thoroughly enjoy what you've put together in the package and I'm hopeful I can get it working with slidify as the applications would be very advantageous. I'll take the question over to the slidify repo and post back here with any response I get for future readers.

**Comment by christophergandrud** [comment]
:+1:
