### ISSUE TITLE
FR: Arrows for links

### ISSUE THREAD

**Issue by kevinykuo** [christophergandrud/networkD3#47]
Something like this: http://bl.ocks.org/d3noob/5141278

I wonder if it makes sense to bake this into the existing `forceNetwork` function?

Also, how much Javascript hacking would be involved?

**Comment by smartinsightsfromdata** [comment]
+1 for arrows

**Comment by christophergandrud** [comment]
I created a branch with basic arrows functionality (https://github.com/christophergandrud/networkD3/tree/directional). The styling is still a bit off.

**Comment by cjyetman** [comment]
this is being worked on in #99. closing this as duplicate
