### ISSUE TITLE
shiny, forceNetwork(..., zoom = TRUE) in browser

### ISSUE THREAD

**Issue by zefmud** [christophergandrud/networkD3#48]
Hello, Christopher!

My application works perfectly wel in browser:  
```
shiny::runGitHub('zefmud/MPs_network')
```
But it stop showing forceNetwork in browser if I use "zoom = TRUE"
```
shiny::runGitHub('zefmud/MPs_network_zoom')
```
Is there any way too zoom while viewing forceNetwork in browser?

Thank you for the wonderful package :)

**Comment by christophergandrud** [comment]
Your example works fine in my browser (Chrome). What are you using?

**Comment by zefmud** [comment]
Mozilla Firefox 38.0.5

**Comment by christophergandrud** [comment]
Hm, I don't know then. This might be an htmlwidgets issue. I would report
it over there.

**Comment by int-ua** [comment]
Errors in Firefox are

```
ReferenceError: redraw is not defined1 forceNetwork.js:85:6
TypeError: link is undefined1 forceNetwork.js:144:6
```

Working fine in Chromium

**Comment by christophergandrud** [comment]
Does this work in Firefox: http://bl.ocks.org/eyaler/10586116

**Comment by int-ua** [comment]
Yes, not a single error.

**Comment by christophergandrud** [comment]
Hm, I think this is an htmlwidgets issue. I would report it over on that repo.
