### ISSUE TITLE
Feature request: bounding box

### ISSUE THREAD

**Issue by paultpearson** [christophergandrud/networkD3#51]
I would like the position of nodes to be constrained within the rectangular bounds of the containing SVG element, as in the example http://bl.ocks.org/mbostock/1129492

Thanks!

**Comment by christophergandrud** [comment]
This looks like it would be pretty easy to implement and not be too off from the core style. Please feel free to make a pull request.

**Comment by csese** [comment]
I made a pull request where I added the feature.
