### ISSUE TITLE
FR: control the opacity of non-hovered text in forceNetwork

### ISSUE THREAD

**Issue by ellisp** [christophergandrud/networkD3#54]
Currently the text of node labels that do not have the mouse hovering over them is set to zero by:
```JavaScript
      .style("opacity", 0)
```

I'd like to be able to have all the text showing as ghosts, retaining the current behaviour of expanding and becoming opacity 1 when hovered over.  This could be done by adding an argument opacityUnclicked to the R function and passing through for use like:
```JavaScript
      .style("opacity", options.opacityUnclicked)
```

Is this desirable?  Happy to submit a pull request.

**Comment by christophergandrud** [comment]
I am trying to keep the package fairly clean of too many complications. But I would take a look at a pull request if you have one.
