### ISSUE TITLE
Feature Request: link strength

### ISSUE THREAD

**Issue by zachcp** [christophergandrud/networkD3#61]
It would be great to be able to specify the link strength, [force.linkStrength([strength])](https://github.com/mbostock/d3/wiki/Force-Layout). For the forceNetwork. perhaps a nother column on the link dataframe could be used to assign forces? In my case I have two types of links and would like to be able to specify strong and weak.

**Comment by christophergandrud** [comment]
Sounds good. I'ld review a pull request.

**Comment by zachcp** [comment]
ok!
