### ISSUE TITLE
Feature request: Nested Treemap

### ISSUE THREAD

**Issue by ignacio82** [christophergandrud/networkD3#65]
I would love to see something like  [this](http://d3plus.org/examples/advanced/9860719/) on networkD3

Thanks!

**Comment by timelyportfolio** [comment]
You want to have a look at [`d3plus`](https://github.com/jpmarindiaz/d3plus) from @jpmarindiaz.  He has made good progress on implementing this widget.

**Comment by timelyportfolio** [comment]
@ignacio82 you also might be interested in the early but sure to improve `d3treeR` (might be rolled into `treemap` http://www.buildingwidgets.com/blog/2015/7/17/week-28-d3treer

**Comment by timelyportfolio** [comment]
@ignacio82 d3treeR should be working again.

**Comment by ignacio82** [comment]
@timelyportfolio great! A couple of questions:

1. Is there a way to show only n (for example 2) levels until you drill down? For example, if you have 10 levels and try to show them all the treemap will be unreadable.  
2. Is there a way to drill up without going down to the last level? In googleVis you can right click

**Comment by timelyportfolio** [comment]
Since `d3treeR` covers this, I'm going to close for now unless @christophergandrud wants this in `networkD3`.
