### ISSUE TITLE
Feature request: control shape of nodes

### ISSUE THREAD

**Issue by ellisp** [christophergandrud/networkD3#66]
I don't have time to do this right now but am noting it down so I remember for later or to get feedback ("terrible idea, don't clutter it up any further"?).  The idea is that eg some nodes would be triangles, some hexagons, etc. - useful for mapping to grouping variables when size and colour are needed for other mappings.

**Comment by christophergandrud** [comment]
Sounds like something worth trying

**Comment by voxnonecho** [comment]
This feature would be very helpful !

**Comment by timelyportfolio** [comment]
related #12
