### ISSUE TITLE
forceNetwork output not displayed in Firefox

### ISSUE THREAD

**Issue by ppernot** [christophergandrud/networkD3#68]
Hi,

the Javascript console in Firefox complains about an unknown "redraw" function.
In fact, the function is defined just after being called in forceNetwork.js (l.84-90).
Shifting the call after the definition solves the problem for me.

There are also a few missing semi-columns in this file...

Thanks for this great package

Pascal

**Comment by christophergandrud** [comment]
Thanks for reporting this. Would it be possible for you to submit a fix via a pull request?

**Comment by ppernot** [comment]
Sorry for the late answer, but I was in vacations.
Anyway, it looks like the issue has now been taken care of by agoldst.

**Comment by christophergandrud** [comment]
Great. I merged in the fix.
