### ISSUE TITLE
Zoom feature for tree graph

### ISSUE THREAD

**Issue by ThoDuyNguyen** [christophergandrud/networkD3#72]
I notice that there is argument for zooming the tree graph. 
Is there any solution for it?
Thank in advance

**Comment by christophergandrud** [comment]
Could you be more specific about what you mean by 'solution for it'?

**Comment by ThoDuyNguyen** [comment]
I mean work-around (or hack) to have zoom feature on tree render.

**Comment by christophergandrud** [comment]
No worries.

Actually, `treeNetwork` is deprecated from version 0.2 (the current build on GitHub). It's replacements `radialNetwork` and `diagonalNetwork` have zooming.
