### ISSUE TITLE
Feature request: Option for all labels displayed on forceNetwork graph

### ISSUE THREAD

**Issue by KathrynPoole** [christophergandrud/networkD3#78]
Am I right in thinking that currently there's no way to display all your node labels at the same time on a forceNetwork? 
The mouseover effect is really good for large graphs, but on smaller ones it would be useful to see all the information at once. 

Thanks!

**Comment by christophergandrud** [comment]
That is correct. If you want to display all node labels at once try using `simpleNetwork` which is intended for smaller networks and so shows all of the labels.
