### ISSUE TITLE
Issues Creating Force Directed Graph

### ISSUE THREAD

**Issue by biotechbeat** [christophergandrud/networkD3#88]
The script runs with no errors, but no graph appears in viewer in R Studio.  Pretty basic usage as you can see below.  I'm using two csv files.

forceNetwork(Links = force_links, Nodes = force_nodes, Source = "source", Target = "target", Value = "value", NodeID = "name", Nodesize = "size", Group = "group", fontSize = 18, fontFamily = "serif")

source,target,value
0,4,2
0,5,2
0,7,2
0,8,2
0,9,2
0,10,2
0,11,2
0,12,2
0,13,2
0,16,2
0,17,2
1,12,2
1,15,2
1,4,2
1,16,2
1,7,2
1,5,2
1,13,2
2,5,2
2,14,2
2,13,2
2,16,2
2,7,2
2,12,2
2,4,2
2,15,2

name,group,size
Person1,0,10
Person2,1,10
Person3,2,10
Task1,3,20
Task2,4,20
Task3,5,20
Task4,6,20
Task5,7,20
Task6,8,20
Task7,9,20
Task8,10,20
Task9,11,20
Task10,12,20
Task11,13,20
Task12,14,20
Task13,15,20

**Comment by timelyportfolio** [comment]
It appears you have `source` and `target` 0 to 17, but only 0 to 15 nodes defined.  Each node in `source` or `target` needs to be defined in `nodes`.  This fixes it, but I just made up nodes `16` and `17` for the demonstration.

```
library(networkD3)

force_links <- read.csv(
  textConnection('
source,target,value
0,4,2
0,5,2
0,7,2
0,8,2
0,9,2
0,10,2
0,11,2
0,12,2
0,13,2
0,16,2
0,17,2
1,12,2
1,15,2
1,4,2
1,16,2
1,7,2
1,5,2
1,13,2
2,5,2
2,14,2
2,13,2
2,16,2
2,7,2
2,12,2
2,4,2
2,15,2                 
'
   )
)

force_nodes <- read.csv(
  textConnection('
name,group,size
Person1,0,10
Person2,1,10
Person3,2,10
Task1,3,20
Task2,4,20
Task3,5,20
Task4,6,20
Task5,7,20
Task6,8,20
Task7,9,20
Task8,10,20
Task9,11,20
Task10,12,20
Task11,13,20
Task12,14,20
Task13,15,20
Task14,16,20
Task15,17,20
'
  ),
  stringsAsFactors = FALSE
)

forceNetwork(
  Links = force_links,
  Nodes = force_nodes,
  Source = "source",
  Target = "target",
  Value = "value",
  NodeID = "name",
  Nodesize = "size",
  Group = "group",
  fontSize = 18,
  fontFamily = "serif"
)
```

**Comment by biotechbeat** [comment]
Works great, thank so much!

**Comment by biotechbeat** [comment]
thanks again

**Comment by timelyportfolio** [comment]
No problem.  @biotechbeat I plan to add more robust error checking and helper functions in a next iteration.  It is not easy or intuitive right now.
