### ISSUE TITLE
Large Sankey Flow Network Not Visualizing

### ISSUE THREAD

**Issue by timarple** [christophergandrud/networkD3#89]
I'm working with a large dataset to generate a Sankey Flow for employee transitions to and from a particular agency. My edgelist is 1070 links long, and I intend to scale this to a much larger dataset; this was largely exploratory. Unfortunately, despite structuring my data identically to the example data in the package, the Sankey Flow will not visualize in the viewer in R, nor does it appear when I zoom or export the blank screen it generates. I found others in StackExchange who had issues visualizing their Sankey Flow with large datasets as well, and was wondering if there has been a solution, or if someone can help me to troubleshoot the issue behind this visualization.

**Comment by timelyportfolio** [comment]
@timarple, glad you are using `networkD3`.  There are three things that I can think of that might be causing your problem.  Is there any way to provide a reproducible example or upload a limited nonworking Sankey to see what is happening?  Could you post `sessionInfo()`?  Could you look in the Chrome Console (F12) in the browser or RStudio Console (right click in Viewer and Inspect) to see if there are any reported JavaScript errors?

- size of graph | Sometimes when a network is very large, Sankeys will not render properly.  Can you try to assign a `height = 5000` and `width = 5000` to see if that produces any output?

- cycles | Until the very newest version of `networkD3`, Sankeys could not handle cycles.  In this case, you will not see output, since your browser gets stuck in an infinite loop.

- improperly specified nodes and links | `sankeyPlot` is not as robust as I would like, so it is pretty specific in how a user defines the network in the arguments.  Inspecting the browser console should provide helpful errors to diagnose this.

Sorry, the answer is not immediately easy, but I think we can work through this one to get some output.

**Comment by timarple** [comment]
Hi, thank you so much for the quick reply. 

My sessionInfo() yielded this: 

> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
 [1] xlsx_0.5.7      xlsxjars_0.6.1  rJava_0.9-7     ROAuth_0.9.6    twitteR_1.1.9  
 [6] tm_0.6-2        NLP_0.1-8       dplyr_0.4.3     plyr_1.8.3      RCurl_1.95-4.7 
[11] bitops_1.0-6    networkD3_0.2.6
loaded via a namespace (and not attached):
 [1] assertthat_0.1    base64enc_0.1-3   bit_1.1-12        bit64_0.9-5       curl_0.9.3       
 [6] DBI_0.3.1         digest_0.6.8      htmltools_0.2.6   htmlwidgets_0.5   httr_1.0.0       
[11] jsonlite_0.9.17   lazyeval_0.1.10   magrittr_1.5      parallel_3.1.3    R6_2.1.1         
[16] Rcpp_0.12.1       rjson_0.2.15      rstudio_0.98.1103 rstudioapi_0.3.1  slam_0.1-32      
[21] stringi_0.5-5     stringr_1.0.0     tools_3.1.3       yaml_2.1.13 

The Inspect function on the viewer yielded no visible JavaScript errors after some searching.

I tried specifying a width and height of 5000, but that did not yield a visualized network. I am using the most recent version of networkD3, so I imagine the cycles should not be an issue. I use the command sankeyNetwork(), not sankeyPlot(), though I cannot find a sankeyPlot() command with the package. 

I was wondering if it might have to do with the encoding of my edgelist and nodeslist; I had to restructure a very large dataset pretty extensively to form an edgelist from it, so there's a chance that, while it is visually identical in structure, there is some underlying issue with the content format. I am unsure how to provide a limited sample here, as I've been told not including some of all of the links can stop the package from providing an output.

**Comment by timelyportfolio** [comment]
Is it possible to try to plot with `forceNetwork`?

**Comment by timarple** [comment]
I attempted this, and got a similarly empty visual. The visual box formats itself with scroll bars as if there were something meant to be there, but it remains empty. I also tried forceNetwork() with your specified height and width values, with no luck.

**Comment by meneos** [comment]
I'm having this same issue with a really small sankey network (the links data frame has 161 observations).

This is my sessionInfo()
```
sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] es_ES.UTF-8/es_ES.UTF-8/es_ES.UTF-8/C/es_ES.UTF-8/es_ES.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] networkD3_0.4   bindrcpp_0.2.2  forcats_0.3.0   stringr_1.3.0   dplyr_0.7.4     purrr_0.2.4     readr_1.1.1     tidyr_0.8.0     tibble_1.4.2    ggplot2_2.2.1  
[11] tidyverse_1.2.1 foreign_0.8-70 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     cellranger_1.1.0 pillar_1.2.1     compiler_3.4.4   plyr_1.8.4       bindr_0.1.1      tools_3.4.4      digest_0.6.15    lubridate_1.7.4  jsonlite_1.5    
[11] nlme_3.1-137     gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.2.0      igraph_1.2.1     psych_1.8.3.3    cli_1.0.0        rstudioapi_0.7   yaml_2.1.18     
[21] parallel_3.4.4   haven_1.1.1      xml2_1.2.0       httr_1.3.1       htmlwidgets_1.2  hms_0.4.2        grid_3.4.4       glue_1.2.0       R6_2.2.2         readxl_1.0.0    
[31] modelr_0.1.1     reshape2_1.4.3   magrittr_1.5     htmltools_0.3.6  scales_0.5.0     rvest_0.3.2      assertthat_0.2.0 mnormt_1.5-5     colorspace_1.3-2 utf8_1.1.3      
[41] stringi_1.1.7    lazyeval_0.2.1   munsell_0.4.3    broom_0.4.4      crayon_1.3.4 
```

**Comment by cjyetman** [comment]
can you please provide a [minimal reproducible example](https://stackoverflow.com/a/5963610/4389763)

**Comment by meneos** [comment]
The thing is that it does work with a data.frame created from scratch. But it does not work with the data I'm working with. If I run the code in this tutorial it does work, so for sure it will work if I create a minimal reproducible example:
https://www.r-bloggers.com/creating-custom-sankey-diagrams-using-r/

If you want to look it up the data I'm using can be downloaded from here:
http://www.cis.es/cis/opencms/ES/formulario.jsp?dwld=/Microdatos/MD3210.zip

and my code is:

```
library(foreign)
library(tidyverse)
library(networkD3)

setwd("/Users/meleiro/Dropbox/MASTER/DATOS/R/CIS")


cis <- read.spss("MD3210/3210.sav", use.value.label=TRUE, to.data.frame=TRUE)

p <- cis %>% group_by(P26AR, VOTOSIMG) %>% summarise(N = n()) %>% mutate(pct = N/sum(N))
p <- p[!is.na(p$P26AR),]

nodes <- data.frame(name = unique(unique(p$P26AR), unique(p$VOTOSIMG)))
links <- data.frame(p)

names(links) = c("source", "target", "value", "value_pct")

sankeyNetwork(Links = links, Nodes = nodes,
              Source = "source", Target = "target",
              Value = "value", NodeID = "name",
              fontSize= 10, nodeWidth = 5, height = 1000, width = 1000)


```

**Comment by cjyetman** [comment]
Please run your script and paste the output of `dput(nodes)` and `dput(links)` here.

**Comment by meneos** [comment]
Here you go.

```
> dput(nodes)
structure(list(name = structure(1:17, .Label = c("PP", "PSOE", 
"Unidos Podemos", "Ciudadanos", "En Comú Podem", "Compromís-Podemos-EUPV", 
"ERC", "Convergència (CDC)", "En Marea", "EAJ-PNV", "EH Bildu", 
"CC-PNC", "Otros partidos", "En blanco", "Voto nulo", "No recuerda", 
"N.C."), class = "factor")), .Names = "name", row.names = c(NA, 
-17L), class = "data.frame")
> dput(links)
structure(list(source = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 4L, 4L, 4L, 4L, 
4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
5L, 6L, 6L, 6L, 6L, 6L, 6L, 6L, 6L, 7L, 7L, 7L, 7L, 7L, 7L, 8L, 
8L, 8L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 10L, 10L, 10L, 11L, 11L, 
12L, 12L, 12L, 13L, 13L, 13L, 13L, 13L, 13L, 13L, 13L, 13L, 13L, 
13L, 14L, 14L, 14L, 14L, 14L, 14L, 14L, 14L, 14L, 15L, 15L, 15L, 
15L, 15L, 16L, 16L, 16L, 16L, 16L, 16L, 16L, 16L, 16L, 16L, 16L, 
16L, 16L, 16L, 17L, 17L, 17L, 17L, 17L, 17L, 17L, 17L, 17L, 17L, 
17L, 17L, 17L, 17L, 17L), .Label = c("PP", "PSOE", "Unidos Podemos", 
"Ciudadanos", "En Comú Podem", "Compromís-Podemos-EUPV", "ERC", 
"Convergència (CDC)", "En Marea", "EAJ-PNV", "EH Bildu", "CC-PNC", 
"Otros partidos", "En blanco", "Voto nulo", "No recuerda", "N.C."
), class = "factor"), target = structure(c(1L, 2L, 4L, 6L, 7L, 
10L, 11L, 19L, 27L, 28L, 29L, 30L, 31L, 1L, 2L, 3L, 4L, 6L, 7L, 
10L, 19L, 26L, 27L, 28L, 29L, 30L, 2L, 3L, 4L, 7L, 19L, 28L, 
29L, 30L, 31L, 1L, 2L, 3L, 4L, 6L, 7L, 11L, 19L, 27L, 28L, 29L, 
31L, 2L, 4L, 6L, 7L, 8L, 19L, 27L, 29L, 30L, 2L, 3L, 4L, 7L, 
8L, 28L, 29L, 30L, 6L, 8L, 9L, 19L, 28L, 29L, 8L, 9L, 29L, 2L, 
4L, 10L, 27L, 28L, 29L, 30L, 4L, 11L, 28L, 11L, 12L, 13L, 27L, 
31L, 1L, 2L, 3L, 4L, 7L, 8L, 19L, 26L, 27L, 28L, 29L, 2L, 3L, 
4L, 6L, 26L, 27L, 28L, 29L, 30L, 3L, 4L, 26L, 28L, 29L, 1L, 2L, 
3L, 4L, 6L, 7L, 8L, 9L, 12L, 27L, 28L, 29L, 30L, 31L, 1L, 2L, 
3L, 4L, 6L, 7L, 8L, 9L, 10L, 26L, 27L, 28L, 29L, 30L, 31L), .Label = c("PP", 
"PSOE", "Unidos Podemos", "Ciudadanos", "IU", "En Comú Podem", 
"Compromís-Podemos", "ERC", "PDeCAT", "En Marea", "EAJ-PNV", 
"EH Bildu", "CC-PNC", "UPN", "Foro Asturias", "Nueva Canarias", 
"BNG", "PCPE", "PACMA", "Los Verdes", "VOX", "Unió Valenciana", 
"Unidos Podemos_duplicated_23", "EQUO", "CUP", "Voto nulo", "Otro partido", 
"En blanco", "No votaría", "No sabe todavía", "N.C."), class = "factor"), 
    value = c(290L, 9L, 86L, 1L, 3L, 1L, 1L, 2L, 8L, 8L, 42L, 
    6L, 2L, 3L, 308L, 9L, 35L, 1L, 1L, 1L, 1L, 1L, 1L, 9L, 53L, 
    4L, 17L, 154L, 9L, 1L, 3L, 6L, 22L, 1L, 2L, 5L, 3L, 3L, 206L, 
    2L, 1L, 1L, 3L, 1L, 9L, 20L, 1L, 2L, 1L, 49L, 2L, 2L, 1L, 
    1L, 3L, 1L, 3L, 1L, 2L, 36L, 1L, 1L, 3L, 1L, 2L, 65L, 4L, 
    1L, 2L, 2L, 7L, 23L, 3L, 2L, 3L, 11L, 2L, 1L, 4L, 1L, 1L, 
    14L, 1L, 2L, 15L, 2L, 1L, 1L, 1L, 2L, 1L, 4L, 2L, 1L, 14L, 
    1L, 4L, 2L, 6L, 1L, 2L, 4L, 2L, 1L, 1L, 34L, 12L, 4L, 2L, 
    3L, 2L, 6L, 4L, 3L, 5L, 1L, 13L, 2L, 2L, 3L, 1L, 1L, 1L, 
    6L, 37L, 5L, 1L, 5L, 6L, 3L, 17L, 2L, 1L, 2L, 1L, 1L, 1L, 
    2L, 8L, 94L, 7L, 24L), value_pct = c(0.631808278867102, 0.0196078431372549, 
    0.187363834422658, 0.00217864923747277, 0.0065359477124183, 
    0.00217864923747277, 0.00217864923747277, 0.00435729847494553, 
    0.0174291938997821, 0.0174291938997821, 0.0915032679738562, 
    0.0130718954248366, 0.00435729847494553, 0.00702576112412178, 
    0.721311475409836, 0.0210772833723653, 0.0819672131147541, 
    0.00234192037470726, 0.00234192037470726, 0.00234192037470726, 
    0.00234192037470726, 0.00234192037470726, 0.00234192037470726, 
    0.0210772833723653, 0.124121779859485, 0.00936768149882904, 
    0.0790697674418605, 0.716279069767442, 0.0418604651162791, 
    0.00465116279069767, 0.013953488372093, 0.027906976744186, 
    0.102325581395349, 0.00465116279069767, 0.00930232558139535, 
    0.0196078431372549, 0.0117647058823529, 0.0117647058823529, 
    0.807843137254902, 0.00784313725490196, 0.00392156862745098, 
    0.00392156862745098, 0.0117647058823529, 0.00392156862745098, 
    0.0352941176470588, 0.0784313725490196, 0.00392156862745098, 
    0.032258064516129, 0.0161290322580645, 0.790322580645161, 
    0.032258064516129, 0.032258064516129, 0.0161290322580645, 
    0.0161290322580645, 0.0483870967741935, 0.0161290322580645, 
    0.0625, 0.0208333333333333, 0.0416666666666667, 0.75, 0.0208333333333333, 
    0.0208333333333333, 0.0625, 0.0208333333333333, 0.0263157894736842, 
    0.855263157894737, 0.0526315789473684, 0.0131578947368421, 
    0.0263157894736842, 0.0263157894736842, 0.212121212121212, 
    0.696969696969697, 0.0909090909090909, 0.0833333333333333, 
    0.125, 0.458333333333333, 0.0833333333333333, 0.0416666666666667, 
    0.166666666666667, 0.0416666666666667, 0.0625, 0.875, 0.0625, 
    0.117647058823529, 0.882352941176471, 0.5, 0.25, 0.25, 0.0263157894736842, 
    0.0526315789473684, 0.0263157894736842, 0.105263157894737, 
    0.0526315789473684, 0.0263157894736842, 0.368421052631579, 
    0.0263157894736842, 0.105263157894737, 0.0526315789473684, 
    0.157894736842105, 0.0163934426229508, 0.0327868852459016, 
    0.0655737704918033, 0.0327868852459016, 0.0163934426229508, 
    0.0163934426229508, 0.557377049180328, 0.19672131147541, 
    0.0655737704918033, 0.117647058823529, 0.176470588235294, 
    0.117647058823529, 0.352941176470588, 0.235294117647059, 
    0.037037037037037, 0.0617283950617284, 0.0123456790123457, 
    0.160493827160494, 0.0246913580246914, 0.0246913580246914, 
    0.037037037037037, 0.0123456790123457, 0.0123456790123457, 
    0.0123456790123457, 0.0740740740740741, 0.45679012345679, 
    0.0617283950617284, 0.0123456790123457, 0.028735632183908, 
    0.0344827586206897, 0.0172413793103448, 0.0977011494252874, 
    0.0114942528735632, 0.00574712643678161, 0.0114942528735632, 
    0.00574712643678161, 0.00574712643678161, 0.00574712643678161, 
    0.0114942528735632, 0.0459770114942529, 0.540229885057471, 
    0.0402298850574713, 0.137931034482759)), .Names = c("source", 
"target", "value", "value_pct"), row.names = c(NA, -142L), class = "data.frame")
```

**Comment by numeroteca** [comment]
@meneos this fixes your problem. I converted converted links table (source and target columns) to integers, following the standard example):
```
   source target value   value_pct
      0      0   290 0.631808279
      0      1     9 0.019607843
      0      3    86 0.187363834
```
you had:
```
 source            target value   value_pct
     PP                PP   290 0.631808279
     PP              PSOE     9 0.019607843
     PP        Ciudadanos    86 0.187363834
```

This would be the code to convert your links data frame:

```
# convert to character
links$source <- as.character(links$source)
links$target <- as.character(links$target)

# changes character by integer
links[links$source=="PP",]$source <- 0
links[links$target=="PP",]$target <- 0
links[links$source=="PSOE",]$source <- 1
links[links$target=="PSOE",]$target <- 1
links[links$source=="Unidos Podemos",]$source <- 2
links[links$target=="Unidos Podemos",]$target <- 2
links[links$source=="Ciudadanos",]$source <- 3
links[links$target=="Ciudadanos",]$target <- 3
# TODO: complete and automatize conversion for all the nodes in nodes

# converts to integer
links$source <- as.integer(links$source)
links$target <- as.integer(links$target)

# slecet avaialbe data
links_clean <- links[!is.na(links$target) & !is.na(links$source) ,]

# plot
sankeyNetwork(Links = links_clean, Nodes = nodes,
              Source = "source", Target = "target",
              Value = "value", NodeID = "name",
              fontSize = 12, nodeWidth = 30)
```

**Comment by cjyetman** [comment]
there are two problems with the data that you are passing to `sankeyNetwork()`...

1. there are numerous nodes referred to in `links$target` that are not present in `nodes$name`

2. `links$source` and `links$target` should be numeric... each value should represent the index of the node in `nodes$name` that it refers to (0-indexed because it is used by JavaScript)

you can build a `nodes` data.frame from your `links` data.frame and then correct`links$source` and `links$target` by matching them to the new `nodes` data.frame like so...

```r
nodes <- data.frame(name = unique(c(as.character(links$source), as.character(links$target))))
links$source <- match(links$source, nodes$name) - 1
links$target <- match(links$target, nodes$name) - 1

sankeyNetwork(Links = links, Nodes = nodes,
              Source = "source", Target = "target",
              Value = "value", NodeID = "name",
              fontSize= 10, nodeWidth = 5, height = 1000, width = 1000)
```

**Comment by meneos** [comment]
Ok, solved. Thanks to both of you! @cjyetman @numeroteca
