### ISSUE TITLE
sankey sizing

### ISSUE THREAD

**Issue by christophergandrud** [christophergandrud/networkD3#90]
@timelyportfolio I should have spotted this sooner, but any idea why the sankey example plot on the [website](http://christophergandrud.github.io/networkD3/#sankey) is so small?

**Comment by timelyportfolio** [comment]
I see now what is happening.  The `title` elements have `getBoundingClientRect()` of `0`.  So sorry, but I will fix and pull momentarily.

**Comment by christophergandrud** [comment]
Perfect. Thanks.
